[package]
name = "hume-scripting"
version = "0.1.0"
edition = "2024"

[features]
# Expose set_data_dir for editor integration tests.
test-util = []

[dependencies]
hume-engine = { path = "../hume-engine" }
hume-platform = { path = "../hume-platform" }
hume-rope = { path = "../hume-rope" }
steel-core = { version = "0.8.2", features = ["custom-hash"] }
termina = "0.3.3"
slotmap = "1"
serde_json.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
tempfile = "3"

