[package]
name = "hume-scripting"
version = "0.1.0"
edition = "2024"

[features]
# Expose set_data_dir for editor integration tests.
test-util = []

[dependencies]
hume-engine = { path = "../hume-engine" }
hume-platform = { path = "../hume-platform" }
steel-core = { version = "0.8.2", features = ["custom-hash"] }
crossterm = "0.29"
slotmap = "1"
tempfile = "3"
serde_json.workspace = true
num-bigint.workspace = true
num-traits.workspace = true

