;;; runtime/scheme/languages.scm — HUME bundled default language identities.
;;;
;;; Evaluated at startup before init.scm.  Override any entry by redefining
;;; it in init.scm — `define-language!` fully replaces the prior registration
;;; for a given name (see init.scm.example for override examples).
;;;
;;; Identity only: extensions, globs, and shebangs.  No tree-sitter grammars
;;; are shipped here — to enable highlighting, call (register-grammar! …) with
;;; paths to a compiled grammar library and highlights query (typically provided
;;; by a plugin).
;;;
;;; Grammar source metadata lives in grammar-sources.scm (loaded by a grammar-
;;; manager plugin, typically core:plum — not by hume at startup).
;;;
;;; Source: helix-editor/helix languages.toml @ 8c41b1160792
;;; Full sync: run scripts/sync-grammars.py after updating helix-pin.scm.

(define-language! "ada" '("adb" "ads"))
(define-language! "adl" '("adl"))
(define-language! "agda" '("agda"))
(define-language! "alloy" '("alloy"))
(define-language! "amber" '("ab"))
(define-language! "astro" '("astro"))
(define-language! "awk" '("awk" "gawk" "nawk" "mawk"))
(define-language! "bash" '("sh" "bash" "ash" "dash" "ksh" "mksh" "zsh" "zshenv" "zlogin" "zlogout" "zprofile" "zshrc" "eclass" "ebuild" "bazelrc" "Renviron" "zsh-theme" "cshrc" "tcshrc" "bashrc_Apple_Terminal" "zshrc_Apple_Terminal") '("i3/config" "sway/config" ".tmux.conf" "tmux.conf" ".sh_history" ".bash_history" ".bash_login" ".bash_logout" ".bash_profile" ".bashrc" ".profile" ".zshenv" ".zlogin" ".zlogout" ".zprofile" ".zshrc" ".zimrc" "APKBUILD" ".bash_aliases" "bash_completion" "bash-completion/completions/*" "bash_completion.d/*" "bin/activate" ".Renviron" ".xprofile" ".xsession" ".xsessionrc" ".yashrc" ".yash_profile" ".hushlogin" ".xinitrc" "xinitrc" ".xserverrc" "xserverrc" "direnvrc") '("sh" "bash" "dash" "zsh"))
(define-language! "basic" '("bas"))
(define-language! "bass" '("bass"))
(define-language! "beancount" '("beancount" "bean"))
(define-language! "bibtex" '("bib"))
(define-language! "bicep" '("bicep" "bicepparam"))
(define-language! "bitbake" '("bb" "bbappend" "bbclass") '("conf/*.conf" "conf/*/*.{inc,conf}" "recipe-*/*/*.inc"))
(define-language! "blade" '("blade") '("*.blade.php"))
(define-language! "blueprint" '("blp"))
(define-language! "bovex" '("bovex" "bibvex"))
(define-language! "c" '("c"))
(define-language! "c-sharp" '("cs" "csx" "cake"))
(define-language! "c3" '("c3" "c3i" "c3t"))
(define-language! "cabal" '("cabal"))
(define-language! "caddyfile" '("Caddyfile" "caddyfile") '("Caddyfile" "Caddyfile.*" "caddyfile" "caddyfile.*"))
(define-language! "cairo" '("cairo"))
(define-language! "capnp" '("capnp"))
(define-language! "cel" '("cel"))
(define-language! "chuck" '() '("*.ck"))
(define-language! "circom" '("circom"))
(define-language! "clarity" '("clar"))
(define-language! "clojure" '("clj" "cljs" "cljc" "clje" "cljr" "cljx" "edn" "boot"))
(define-language! "cmake" '("cmake") '("CMakeLists.txt"))
(define-language! "codeql" '("ql" "qll"))
(define-language! "comment")
(define-language! "common-lisp" '("lisp" "asd" "cl" "l" "lsp" "ny" "podsl" "ros" "sexp") '() '("lisp" "sbcl" "ccl" "clisp" "ecl"))
(define-language! "cpon" '("cpon" "cp"))
(define-language! "cpp" '("cc" "hh" "c++" "cpp" "hpp" "h" "ipp" "tpp" "cxx" "hxx" "ixx" "txx" "ino" "C" "H" "cu" "cuh" "cppm" "h++" "ii" "inl") '(".hpp.in" ".h.in"))
(define-language! "cross-config" '() '("Cross.toml"))
(define-language! "crystal" '("cr"))
(define-language! "css" '("css"))
(define-language! "csv" '("csv"))
(define-language! "cue" '("cue"))
(define-language! "cylc" '("cylc") '("suite.rc"))
(define-language! "cython" '("pxd" "pxi" "pyx"))
(define-language! "d" '("d" "dd"))
(define-language! "dart" '("dart"))
(define-language! "dbml" '("dbml"))
(define-language! "debian" '("dsc" "changes") '("debian/**/control" "etc/apt/sources.list.d/*.sources"))
(define-language! "devicetree" '("dts" "dtsi"))
(define-language! "dhall" '("dhall"))
(define-language! "diff" '("diff" "patch" "rej"))
(define-language! "djot" '("dj" "djot"))
(define-language! "docker-bake" '() '("docker-bake.hcl" "docker-bake.override.hcl"))
(define-language! "docker-compose" '() '("docker-compose.yaml" "docker-compose.yml" "compose.yaml" "compose.yml"))
(define-language! "dockerfile" '("Dockerfile" "dockerfile" "Containerfile" "containerfile") '("Dockerfile" "Dockerfile.*" "dockerfile" "dockerfile.*" "Containerfile" "Containerfile.*" "containerfile" "containerfile.*"))
(define-language! "dot" '("dot"))
(define-language! "doxyfile" '() '("Doxyfile"))
(define-language! "drools" '("drl"))
(define-language! "dtd" '("dtd" "ent"))
(define-language! "dune" '() '("dune-project" "dune"))
(define-language! "dunstrc" '() '("dunst/dunstrc"))
(define-language! "earthfile" '() '("Earthfile"))
(define-language! "ebnf" '("ebnf"))
(define-language! "edoc" '("edoc" "edoc.in"))
(define-language! "eex" '("eex"))
(define-language! "eiffel" '("e"))
(define-language! "ejs" '("ejs"))
(define-language! "elisp" '("el"))
(define-language! "elixir" '("ex" "exs") '("mix.lock") '("elixir"))
(define-language! "elm" '("elm"))
(define-language! "elvish" '("elv") '() '("elvish"))
(define-language! "embedded-perl" '("ep") '("*.html.ep"))
(define-language! "env" '() '(".env" ".env.*" ".envrc" ".envrc.*" "_environment" "_environment-*" "_environment.local" "_environment.required" ".bazeliskrc" ".gitlab-ci-local-env"))
(define-language! "erb" '("erb"))
(define-language! "erlang" '("erl" "hrl" "app") '("rebar.config" "rebar.lock" "*.app.src") '("escript"))
(define-language! "esdl" '("gel" "esdl"))
(define-language! "fennel" '("fnl" "fnlm") '() '("fennel"))
(define-language! "fga" '("fga") '("fga.mod"))
(define-language! "fidl" '("fidl"))
(define-language! "fish" '("fish") '() '("fish"))
(define-language! "flatbuffers" '("fbs"))
(define-language! "forth" '("fs" "forth" "fth" "4th"))
(define-language! "fortran" '("f" "for" "f90" "f95" "f03" "F" "F90" "F95" "F03"))
(define-language! "freebasic" '("bas" "bi"))
(define-language! "fsharp" '("fs" "fsx" "fsi" "fsscript"))
(define-language! "gas" '("s"))
(define-language! "gdscript" '("gd"))
(define-language! "gemini" '("gmi"))
(define-language! "gherkin" '("feature"))
(define-language! "ghostty" '("ghostty") '("ghostty/config"))
(define-language! "git-attributes" '() '(".gitattributes" ".config/git/attributes"))
(define-language! "git-cliff-config" '() '("cliff.toml"))
(define-language! "git-commit" '() '("COMMIT_EDITMSG" "MERGE_MSG" "TAG_EDITMSG"))
(define-language! "git-config" '("gitconfig") '(".gitmodules" "gitconfig" ".gitconfig" ".git/config" ".config/git/config" ".git/modules/*/config" "config.worktree"))
(define-language! "git-ignore" '() '(".gitignore_global" "git/ignore" ".git/info/exclude" ".ignore" "CODEOWNERS" ".config/helix/ignore" ".helix/ignore" ".*ignore" ".git-blame-ignore-revs"))
(define-language! "git-notes" '() '("NOTES_EDITMSG" "EDIT_DESCRIPTION"))
(define-language! "git-rebase" '() '("git-rebase-todo"))
(define-language! "github-action" '() '(".github/workflows/*.yaml" ".github/workflows/*.yml"))
(define-language! "gitlab-ci" '() '(".gitlab-ci.yml"))
(define-language! "gjs" '("gjs"))
(define-language! "gleam" '("gleam"))
(define-language! "glimmer" '() '("{app,addon}/{components,templates}/*.hbs"))
(define-language! "glsl" '("glsl" "vert" "tesc" "tese" "geom" "frag" "comp"))
(define-language! "gn" '("gn" "gni"))
(define-language! "gnuplot" '("gnuplot" "plot" "plt"))
(define-language! "go" '("go"))
(define-language! "go-format-string")
(define-language! "godot-resource" '("tscn" "tres" "godot" "gdextension"))
(define-language! "gomod" '() '("go.mod"))
(define-language! "gotmpl" '("gotmpl"))
(define-language! "gowork" '() '("go.work"))
(define-language! "gpr" '("gpr"))
(define-language! "graphql" '("gql" "graphql" "graphqls"))
(define-language! "gren" '("gren"))
(define-language! "groovy" '("gradle" "groovy" "jenkinsfile") '("Jenkinsfile" "Jenkinsfile.*") '("groovy"))
(define-language! "gts" '("gts"))
(define-language! "hare" '("ha"))
(define-language! "haskell" '("hs" "hs-boot" "hsc") '() '("runhaskell" "stack"))
(define-language! "haskell-literate" '("lhs") '() '("runhaskell" "stack"))
(define-language! "haskell-persistent" '("persistentmodels"))
(define-language! "haxe" '("hx"))
(define-language! "hcl" '("hcl" "tf" "nomad"))
(define-language! "hdl" '("hdl"))
(define-language! "heex" '("heex"))
(define-language! "helm" '() '("templates/*.yaml" "templates/*.yml" "templates/_*.tpl" "templates/NOTES.txt"))
(define-language! "hocon" '() '("**/src/*/resources/**/*.conf" "*scalafmt*.conf" "*scalafix*.conf"))
(define-language! "hoon" '("hoon"))
(define-language! "hosts" '() '("hosts"))
(define-language! "html" '("html" "htm" "shtml" "xhtml" "xht" "jsp" "asp" "aspx" "jshtm" "volt" "rhtml" "cshtml"))
(define-language! "htmldjango")
(define-language! "hurl" '("hurl"))
(define-language! "hy" '("hy"))
(define-language! "hyprlang" '() '("hypr/*.conf"))
(define-language! "idris" '("idr"))
(define-language! "iex" '("iex"))
(define-language! "ini" '("ini" "desktop" "properties" "cfg" "directory") '("mimeapps.list" ".editorconfig" ".npmrc" "hgrc" "npmrc" "rclone.conf" ".aws/config" ".wslconfig" ".buckconfig" ".buckconfig.local" ".buckconfig.d/*" "/etc/buckconfig" "/etc/buckconfig.d/*"))
(define-language! "ink" '("ink"))
(define-language! "inko" '("inko"))
(define-language! "janet" '("cgen" "janet" "jdn") '() '("janet"))
(define-language! "java" '("java" "jav" "pde"))
(define-language! "javascript" '("js" "mjs" "cjs" "rules" "es6" "pac" "gs") '(".node_repl_history" "jakefile") '("node"))
(define-language! "jinja" '("jinja" "jinja2" "j2"))
(define-language! "jjconfig" '() '("jj/config.toml" "jj/**/*.toml" ".jj/repo/*.toml"))
(define-language! "jjdescription" '() '("*.jjdescription"))
(define-language! "jjrevset" '("jjrevset"))
(define-language! "jjtemplate" '("jjtemplate"))
(define-language! "jq" '("jq"))
(define-language! "jsdoc" '("jsdoc"))
(define-language! "json" '("json" "arb" "ipynb" "geojson" "gltf" "webmanifest" "js.map" "ts.map" "css.map" "jsonl" "avsc" "ldtk" "ldtkl" "sublime-build" "sublime-color-scheme" "sublime-commands" "sublime-completions" "sublime-keymap" "sublime-macro" "sublime-menu" "sublime-mousemap" "sublime-project" "sublime-settings" "sublime-theme" "sublime-workspace" "code-workspace") '("flake.lock" ".babelrc" ".bowerrc" ".jscrc" ".jslintrc" ".vuerc" "composer.lock" ".watchmanconfig" ".swift-format" ".pytest_cache/v/cache/*" "devenv.lock" "devbox.lock" "manifest.lock" "deno.lock"))
(define-language! "json-ld" '("jsonld"))
(define-language! "json5" '("json5"))
(define-language! "jsonc" '("jsonc") '("{t,j}sconfig.json" "bun.lock" ".devcontainer.json" "devcontainer.json" ".vscode/*.json"))
(define-language! "jsonnet" '("libsonnet" "jsonnet"))
(define-language! "jsx" '("jsx"))
(define-language! "julia" '("jl") '() '("julia"))
(define-language! "just" '("just") '("justfile" "Justfile" ".justfile" ".Justfile"))
(define-language! "kcl" '("kcl"))
(define-language! "kconfig" '("Kconfig") '("Kconfig.*"))
(define-language! "kdl" '("kdl"))
(define-language! "klog" '("klg"))
(define-language! "koka" '("kk"))
(define-language! "kotlin" '("kt" "kts"))
(define-language! "koto" '("koto"))
(define-language! "latex" '("tex" "dtx" "ins" "sty" "cls" "Rd" "bbx" "cbx"))
(define-language! "ld" '("ld"))
(define-language! "ldif" '("ldif"))
(define-language! "lean" '("lean"))
(define-language! "ledger" '("ldg" "ledger" "journal"))
(define-language! "less" '("less"))
(define-language! "llvm" '("ll"))
(define-language! "llvm-mir")
(define-language! "llvm-mir-yaml" '("mir"))
(define-language! "log" '("log"))
(define-language! "lpf" '("lpf"))
(define-language! "lua" '("lua" "rockspec") '() '("lua" "luajit"))
(define-language! "lua-format-string")
(define-language! "luap")
(define-language! "luau" '("luau"))
(define-language! "mail" '("eml"))
(define-language! "make" '("make" "mk" "mak") '("Makefile" "makefile" "GNUmakefile" "OCamlMakefile") '("make" "gmake"))
(define-language! "markdoc" '("mdoc"))
(define-language! "markdown" '("md" "livemd" "markdown" "mdx" "mkd" "mkdn" "mdwn" "mdown" "markdn" "mdtxt" "mdtext" "workbook") '("PULLREQ_EDITMSG"))
(define-language! "markdown-rustdoc")
(define-language! "markdown.inline")
(define-language! "matlab" '("m") '() '("octave-cli" "matlab"))
(define-language! "mermaid" '("mermaid" "mmd"))
(define-language! "meson" '() '("meson.build" "meson.options" "meson_options.txt"))
(define-language! "mint" '("mint"))
(define-language! "miseconfig" '() '("mise.toml" ".mise.toml" "mise.*.toml" ".mise.*.toml" "mise/config.toml" ".mise/config.toml" ".config/mise.toml" ".config/mise/conf.d/*.toml"))
(define-language! "mojo" '("mojo" "🔥"))
(define-language! "move" '("move"))
(define-language! "msbuild" '("proj" "vbproj" "csproj" "fsproj" "targets" "props"))
(define-language! "nasm" '("asm" "S" "nasm"))
(define-language! "nearley" '("ne"))
(define-language! "nestedtext" '("nt"))
(define-language! "nginx" '() '("sites-available/*.conf" "sites-enabled/*.conf" "nginx.conf" "conf.d/*.conf"))
(define-language! "nickel" '("ncl"))
(define-language! "nim" '("nim" "nims" "nimble"))
(define-language! "nix" '("nix"))
(define-language! "nu" '("nu" "nuon") '() '("nu"))
(define-language! "nunjucks" '("njk"))
(define-language! "ocaml" '("ml") '() '("ocaml" "ocamlrun" "ocamlscript"))
(define-language! "ocaml-interface" '("mli"))
(define-language! "odin" '("odin"))
(define-language! "ohm" '("ohm"))
(define-language! "opencl" '("cl"))
(define-language! "openscad" '("scad"))
(define-language! "org" '("org"))
(define-language! "pascal" '("pas" "pp" "inc" "lpr" "lfm"))
(define-language! "passwd" '() '("passwd"))
(define-language! "pem" '("pem" "cert" "crt"))
(define-language! "penrose" '("substance" "style" "domain"))
(define-language! "perl" '("pl" "pm" "t" "psgi" "raku" "rakumod" "rakutest" "rakudoc" "nqp" "p6" "pl6" "pm6") '("latexmkrc" ".latexmkrc") '("perl"))
(define-language! "pest" '("pest"))
(define-language! "php" '("php" "inc" "php4" "php5" "phtml" "ctp") '() '("php"))
(define-language! "php-only")
(define-language! "picat" '("pi" "picat") '() '("picat"))
(define-language! "pip-requirements" '() '("requirements.txt" "constraints.txt"))
(define-language! "pkgbuild" '() '("PKGBUILD"))
(define-language! "pkl" '("pkl" "pcf") '("PklProject"))
(define-language! "po" '("po" "pot"))
(define-language! "pod" '("pod"))
(define-language! "ponylang" '("pony"))
(define-language! "powershell" '("ps1" "psm1" "psd1" "pscc" "psrc") '() '("pwsh" "powershell"))
(define-language! "prisma" '("prisma"))
(define-language! "prolog" '("pl" "prolog") '() '("swipl"))
(define-language! "properties" '("properties" "prefs"))
(define-language! "protobuf" '("proto"))
(define-language! "proverif" '("pv"))
(define-language! "prql" '("prql"))
(define-language! "ptx" '("ptx"))
(define-language! "pug" '("pug"))
(define-language! "purescript" '("purs"))
(define-language! "python" '("py" "pyi" "py3" "pyw" "ptl" "rpy" "cpy" "ipy" "pyt") '(".python_history" ".pythonstartup" ".pythonrc" "*SConstruct" "*SConscript" "*sconstruct") '("python" "uv"))
(define-language! "qml" '("qml"))
(define-language! "qmv" '() '("/tmp/qmv*"))
(define-language! "quarto" '("qmd"))
(define-language! "quint" '("qnt"))
(define-language! "r" '("r" "R") '(".Rprofile" "Rprofile.site" ".RHistory") '("r" "R"))
(define-language! "racket" '("rkt" "rktd" "rktl" "scrbl" "zuo") '() '("racket" "zuo"))
(define-language! "regex" '("regex") '(".Rbuildignore"))
(define-language! "rego" '("rego"))
(define-language! "rescript" '("res"))
(define-language! "ripple" '("ripple"))
(define-language! "rmarkdown" '("rmd" "Rmd"))
(define-language! "robot" '("robot" "resource"))
(define-language! "robots.txt" '() '("robots.txt"))
(define-language! "ron" '("ron"))
(define-language! "rpmspec" '("spec"))
(define-language! "rshtml" '() '("*.rs.html"))
(define-language! "rst" '("rst"))
(define-language! "ruby" '("rb" "rake" "irb" "gemspec" "rabl" "jbuilder" "jb" "podspec" "rjs" "rbi" "rbs") '("rakefile" "gemfile" "Rakefile" "Gemfile" "Podfile" "Vagrantfile" "Brewfile" "*.Brewfile" "Guardfile" "Capfile" "Cheffile" "Hobofile" "Appraisals" "Rantfile" "Berksfile" "Berksfile.lock" "Thorfile" "Puppetfile" "Fastfile" "Appfile" "Deliverfile" "Matchfile" "Scanfile" "Snapfile" "Gymfile" ".irbrc") '("ruby"))
(define-language! "rust" '("rs") '() '("rust-script" "cargo"))
(define-language! "rust-format-args")
(define-language! "rust-format-args-macro")
(define-language! "sage" '("sage"))
(define-language! "scala" '("scala" "sbt" "sc"))
(define-language! "scfg" '() '("kanshi/config"))
(define-language! "scheme" '("ss" "scm" "sld") '() '("scheme" "guile" "chicken"))
(define-language! "scss" '("scss"))
(define-language! "shellcheckrc" '() '("shellcheckrc" ".shellcheckrc"))
(define-language! "slang" '("slang"))
(define-language! "slint" '("slint"))
(define-language! "slisp" '("sl"))
(define-language! "smali" '("smali"))
(define-language! "smithy" '("smithy"))
(define-language! "sml" '("sml"))
(define-language! "snakemake" '("smk") '("Snakefile"))
(define-language! "solidity" '("sol"))
(define-language! "sourcepawn" '("sp" "inc"))
(define-language! "spade" '("spade"))
(define-language! "spicedb" '("zed"))
(define-language! "sql" '("sql" "dsql"))
(define-language! "sshclientconfig" '() '(".ssh/config" "/etc/ssh/ssh_config" "ssh_config.d/*.conf"))
(define-language! "starlark" '("bzl" "bazel" "star") '("BUILD" "BUCK" "BUILD.*" "WORKSPACE" "WORKSPACE.bzlmod" "PACKAGE"))
(define-language! "strace" '("strace"))
(define-language! "strictdoc" '("sdoc" "sgra"))
(define-language! "styx" '("styx"))
(define-language! "supercollider" '("scd" "sc" "quark"))
(define-language! "svelte" '("svelte"))
(define-language! "sway" '("sw"))
(define-language! "swift" '("swift" "swiftinterface"))
(define-language! "systemd" '("service" "automount" "device" "mount" "nspawn" "path" "scope" "slice" "socket" "swap" "target" "timer" "container" "kube" "network" "volume" "build" "image") '("systemd/**/*.conf" "containers/systemd/**/*.pod"))
(define-language! "systemverilog" '("sv" "svh"))
(define-language! "t32" '("cmm" "t32"))
(define-language! "tablegen" '("td"))
(define-language! "tact" '("tact"))
(define-language! "task" '("task"))
(define-language! "tcl" '("tcl") '() '("tclsh" "tclish" "jimsh" "wish"))
(define-language! "teal" '("tl"))
(define-language! "templ" '("templ"))
(define-language! "tera" '("tera"))
(define-language! "textproto" '("txtpb" "textpb" "textproto"))
(define-language! "tfvars" '("tfvars"))
(define-language! "thrift" '("thrift"))
(define-language! "tilt" '("tiltfile") '("Tiltfile"))
(define-language! "tlaplus" '("tla"))
(define-language! "todotxt" '("todotxt") '("*.todo.txt"))
(define-language! "toml" '("toml") '("pdm.lock" "poetry.lock" "Cargo.lock" "uv.lock" "containers.conf" "containers.conf.d/*.conf" "containers.conf.modules/*.conf" "mounts.conf" "policy.conf" "registries.conf" "storage.conf"))
(define-language! "tql" '("tql"))
(define-language! "tsq" '() '("queries/*.scm" "injections.scm" "highlights.scm" "indents.scm" "textobjects.scm" "locals.scm" "tags.scm"))
(define-language! "tsx" '("tsx"))
(define-language! "twig" '("twig"))
(define-language! "typescript" '("ts" "mts" "cts") '() '("deno" "bun" "ts-node"))
(define-language! "typespec" '("tsp"))
(define-language! "typst" '("typst" "typ"))
(define-language! "ungrammar" '("ungram" "ungrammar"))
(define-language! "unison" '("u"))
(define-language! "uxntal" '("tal"))
(define-language! "v" '("v" "vv" "vsh") '() '("v run"))
(define-language! "vala" '("vala" "vapi"))
(define-language! "vento" '("vto"))
(define-language! "verilog" '("v" "vh"))
(define-language! "vhdl" '("vhd" "vhdl"))
(define-language! "vhs" '("tape"))
(define-language! "vim" '("vim") '(".vimrc" ".nvimrc" ".exrc"))
(define-language! "vue" '("vue"))
(define-language! "wast" '("wast"))
(define-language! "wat" '("wat"))
(define-language! "webc" '("webc"))
(define-language! "werk" '("werk") '("Werkfile"))
(define-language! "wesl" '("wesl"))
(define-language! "wgsl" '("wgsl"))
(define-language! "wikitext" '("wikimedia" "mediawiki" "wikitext"))
(define-language! "wit" '("wit"))
(define-language! "woodpecker-ci" '() '(".woodpecker.yaml" ".woodpecker/*.yaml" ".woodpecker/*.yml"))
(define-language! "wren" '("wren"))
(define-language! "xit" '("xit"))
(define-language! "xml" '("ascx" "atom" "axaml" "axml" "bpmn" "checkstyle" "cpt" "csl" "csproj.user" "dita" "ditamap" "dtml" "fods" "fodt" "fxml" "gir" "glif" "gml" "gpx" "iml" "isml" "itermcolors" "jmx" "kml" "launch" "menu" "mobileconfig" "mpd" "musicxml" "mxml" "ncx" "nuspec" "opml" "osc" "osm" "plist" "policy" "pt" "publishsettings" "pubxml" "pubxml.user" "rbxlx" "rbxmx" "resx" "rng" "rss" "shproj" "smil" "storyboard" "sublime-snippet" "svg" "terminal" "tld" "tmx" "ui" "vbproj.user" "vcxproj" "vcxproj.filters" "wixproj" "wsdl" "wxi" "wxs" "xaml" "xbl" "xib" "xlf" "xliff" "xml" "xmp" "xoml" "xpdl" "xrc" "xsd" "xsl" "xul") '("*.tm[Ll]anguage" "*.tm[Pp]references" "*.tm[Tt]heme"))
(define-language! "xtc" '("xtc" "xpc" "xoa"))
(define-language! "yaml" '("yml" "yaml" "sublime-syntax" "bu") '(".prettierrc" ".clangd" ".clang-format" ".clang-tidy" ".gem/credentials" ".kube/config" ".kube/kuberc" "yarn.lock" ".stylelintrc" ".puppeteerrc"))
(define-language! "yara" '("yara" "yar"))
(define-language! "yuck" '("yuck"))
(define-language! "zig" '("zig" "zon"))
