;;; runtime/scheme/lsp-servers.scm — HUME bundled LSP server registration catalog.
;;;
;;; PURE DATA. One literal sexpr — a list of per-server tagged alists:
;;;
;;;   (name
;;;    (languages (lang-name root-marker…)…)
;;;    (command . cmd)
;;;    (args arg…)
;;;    (config . json-string))
;;;
;;; `args` is the empty tail `(args)` (never #f) when the server takes none.
;;; `config` is Helix's `[language-server.*.config]` table for this server,
;;; copied verbatim — the *entire* tail is `(config)` (never a dotted pair)
;;; when Helix has no config for it; otherwise `(config . "...")`, a single
;;; canonical (sort_keys) JSON-encoded string. `core:lsp/registration.scm`
;;; delivers it two ways, exactly as Helix does: as `initializationOptions`
;;; (the path that actually configures most servers) and as
;;; `register-lsp-server!`'s `#:settings` (answers `workspace/configuration`
;;; pulls — a miss is expected and harmless for servers whose config isn't
;;; nested under their own name). The runtime catalog loader parses the
;;; JSON string with the `(json-parse)` builtin at load time, once, rather
;;; than every plugin needing its own nested-alist/vector-array reader for a
;;; JSON object embedded as Scheme data. All fields are fully canonicalised;
;;; no defaults are applied at read time. Read via the R7RS idiom from any
;;; plugin:
;;;
;;;   (define *lsp-servers*
;;;     (call-with-input-file
;;;       (path-join (runtime-dir) "scheme" "lsp-servers.scm")
;;;       read))
;;;
;;; One server per language — Helix's first-listed ("primary") language-server
;;; only; see docs/LSP-INSTALL.md "v1 scope" for the multi-server rationale.
;;; Install sources (download/build info) live in lsp-sources.scm, joined by
;;; server name.
;;;
;;; Source: helix-editor/helix languages.toml @ f6f3eb1fe4a7
;;; Full sync: run scripts/sync-grammars.py after updating helix-pin.scm.

(
 ("actions-language-server" (languages ("github-action")) (command . "actions-languageserver") (args "--stdio") (config . "{\"sessionToken\": \"\"}"))
 ("ada-gpr-language-server" (languages ("gpr" "alire.toml")) (command . "ada_language_server") (args "--language-gpr") (config))
 ("ada-language-server" (languages ("ada" "alire.toml")) (command . "ada_language_server") (args) (config))
 ("amber-lsp" (languages ("amber")) (command . "amber-lsp") (args) (config))
 ("asm-lsp" (languages ("nasm") ("gas")) (command . "asm-lsp") (args) (config))
 ("astro-ls" (languages ("astro")) (command . "astro-ls") (args "--stdio") (config . "{\"typescript\": {\"tsdk\": \"node_modules/typescript/lib\"}}"))
 ("awk-language-server" (languages ("awk")) (command . "awk-language-server") (args) (config))
 ("bash-language-server" (languages ("bash")) (command . "bash-language-server") (args "start") (config))
 ("bass" (languages ("bass")) (command . "bass") (args "--lsp") (config))
 ("beancount-language-server" (languages ("beancount")) (command . "beancount-language-server") (args) (config))
 ("bicep-langserver" (languages ("bicep")) (command . "bicep-langserver") (args) (config))
 ("bitbake-language-server" (languages ("bitbake")) (command . "bitbake-language-server") (args) (config))
 ("blueprint-compiler" (languages ("blueprint")) (command . "blueprint-compiler") (args "lsp") (config))
 ("buf" (languages ("protobuf")) (command . "buf") (args "lsp" "serve" "--timeout" "0") (config))
 ("c3-lsp" (languages ("c3" "project.json")) (command . "c3-lsp") (args) (config))
 ("cairo-language-server" (languages ("cairo")) (command . "cairo-language-server") (args) (config))
 ("circom-lsp" (languages ("circom" "package.json")) (command . "circom-lsp") (args) (config))
 ("cl-lsp" (languages ("common-lisp")) (command . "cl-lsp") (args) (config))
 ("clangd" (languages ("c") ("cpp") ("opencl")) (command . "clangd") (args) (config))
 ("clarinet" (languages ("clarity" "Clarinet.toml")) (command . "clarinet") (args "lsp") (config))
 ("clojure-lsp" (languages ("clojure" "project.clj" "build.boot" "deps.edn" "shadow-cljs.edn")) (command . "clojure-lsp") (args) (config))
 ("codeql" (languages ("codeql")) (command . "codeql") (args "execute" "language-server" "--check-errors=ON_CHANGE") (config))
 ("commit-lsp" (languages ("git-commit")) (command . "commit-lsp") (args "run") (config))
 ("crystalline" (languages ("crystal" "shard.yml" "shard.lock")) (command . "crystalline") (args "--stdio") (config))
 ("cs" (languages ("smithy" "smithy-build.json")) (command . "cs") (args "launch" "--contrib" "smithy-language-server" "--" "0") (config))
 ("cuelsp" (languages ("cue" "cue.mod")) (command . "cue") (args "lsp" "serve") (config))
 ("dart" (languages ("dart" "pubspec.yaml")) (command . "dart") (args "language-server" "--client-id=helix") (config))
 ("debian-lsp" (languages ("debian")) (command . "debian-lsp") (args) (config))
 ("dhall-lsp-server" (languages ("dhall")) (command . "dhall-lsp-server") (args) (config))
 ("djlsp" (languages ("htmldjango" "manage.py")) (command . "djlsp") (args) (config))
 ("docker-compose-langserver" (languages ("docker-compose" "docker-compose.yaml" "docker-compose.yml" "compose.yaml" "compose.yml")) (command . "docker-compose-langserver") (args "--stdio") (config))
 ("docker-langserver" (languages ("dockerfile" "Dockerfile" "Containerfile")) (command . "docker-langserver") (args "--stdio") (config))
 ("docker-language-server" (languages ("docker-bake")) (command . "docker-language-server") (args "start" "--stdio") (config))
 ("dot-language-server" (languages ("dot")) (command . "dot-language-server") (args "--stdio") (config))
 ("drools-lsp" (languages ("drools" "pom.xml" ".git")) (command . "drools-lsp") (args) (config))
 ("dts-lsp" (languages ("devicetree")) (command . "dts-lsp") (args) (config))
 ("earthlyls" (languages ("earthfile" "Earthfile")) (command . "earthlyls") (args) (config))
 ("ebnfer" (languages ("ebnf")) (command . "ebnfer") (args) (config))
 ("eiffel-language-server" (languages ("eiffel")) (command . "eiffel-language-server") (args) (config))
 ("elixir-ls" (languages ("elixir" "mix.exs" "mix.lock") ("heex" "mix.exs" "mix.lock")) (command . "elixir-ls") (args) (config . "{\"elixirLS\": {\"dialyzerEnabled\": false}}"))
 ("elm-language-server" (languages ("elm" "elm.json")) (command . "elm-language-server") (args) (config))
 ("elvish" (languages ("elvish")) (command . "elvish") (args "-lsp") (config))
 ("ember-language-server" (languages ("glimmer" "package.json" "ember-cli-build.js")) (command . "ember-language-server") (args "--stdio") (config))
 ("erlang-ls" (languages ("erlang" "rebar.config")) (command . "erlang_ls") (args) (config))
 ("fennel-ls" (languages ("fennel")) (command . "fennel-ls") (args) (config))
 ("fish-lsp" (languages ("fish")) (command . "fish-lsp") (args "start") (config))
 ("forc" (languages ("sway" "Forc.toml" "Forc.lock")) (command . "forc") (args "lsp") (config))
 ("forth-lsp" (languages ("forth")) (command . "forth-lsp") (args) (config))
 ("fortls" (languages ("fortran" "fpm.toml")) (command . "fortls") (args "--lowercase_intrinsics") (config))
 ("fsharp-ls" (languages ("fsharp" "*.slnx" "*.sln" "*.fsproj")) (command . "fsautocomplete") (args) (config . "{\"AutomaticWorkspaceInit\": true}"))
 ("ghostty-ls" (languages ("ghostty")) (command . "ghostty-ls") (args) (config))
 ("gleam" (languages ("gleam" "gleam.toml")) (command . "gleam") (args "lsp") (config))
 ("glsl_analyzer" (languages ("glsl")) (command . "glsl_analyzer") (args) (config))
 ("godot" (languages ("gdscript" "project.godot")) (command . "ncat") (args "127.0.0.1" "6005") (config))
 ("gopls" (languages ("go" "go.work" "go.mod") ("gomod") ("gotmpl") ("gowork")) (command . "gopls") (args) (config . "{\"hints\": {\"assignVariableTypes\": true, \"compositeLiteralFields\": true, \"constantValues\": true, \"functionTypeParameters\": true, \"parameterNames\": true, \"rangeVariableTypes\": true}}"))
 ("graphql-language-service" (languages ("graphql")) (command . "graphql-lsp") (args "server" "-m" "stream") (config))
 ("hare-lsp" (languages ("hare")) (command . "hare-lsp") (args "-S") (config))
 ("haskell-language-server" (languages ("haskell" "Setup.hs" "stack.yaml" "cabal.project" "hie.yaml") ("haskell-literate" "Setup.hs" "stack.yaml" "cabal.project" "hie.yaml") ("cabal" "cabal.project" "Setup.hs")) (command . "haskell-language-server-wrapper") (args "--lsp") (config))
 ("hdls" (languages ("hdl")) (command . "hdls") (args) (config))
 ("helm_ls" (languages ("helm" "Chart.yaml")) (command . "helm_ls") (args "serve") (config))
 ("hyprls" (languages ("hyprlang" "hyprland.conf")) (command . "hyprls") (args) (config))
 ("hyuga" (languages ("hy" "pyproject.toml")) (command . "hyuga") (args) (config))
 ("idris2-lsp" (languages ("idris")) (command . "idris2-lsp") (args) (config))
 ("intelephense" (languages ("php" "composer.json" "index.php")) (command . "intelephense") (args "--stdio") (config))
 ("jdtls" (languages ("java" "pom.xml" "build.gradle" "build.gradle.kts")) (command . "jdtls") (args) (config))
 ("jq-lsp" (languages ("jq")) (command . "jq-lsp") (args) (config))
 ("jsonnet-language-server" (languages ("jsonnet" "jsonnetfile.json")) (command . "jsonnet-language-server") (args "-t" "--lint") (config))
 ("julia" (languages ("julia" "Manifest.toml" "Project.toml")) (command . "julia") (args "--startup-file=no" "--history-file=no" "--quiet" "-e" "using LanguageServer; runserver()") (config))
 ("just-lsp" (languages ("just")) (command . "just-lsp") (args) (config))
 ("kcl-lsp" (languages ("kcl")) (command . "kcl-language-server") (args "server" "--stdio") (config))
 ("koka" (languages ("koka")) (command . "koka") (args "--language-server" "--lsstdio") (config))
 ("kotlin-language-server" (languages ("kotlin" "settings.gradle" "settings.gradle.kts")) (command . "kotlin-language-server") (args) (config))
 ("koto-ls" (languages ("koto")) (command . "koto-ls") (args) (config))
 ("lean" (languages ("lean" "lakefile.lean" "lakefile.toml")) (command . "lake") (args "serve") (config))
 ("lua-language-server" (languages ("lua" ".luarc.json" ".luacheckrc" ".stylua.toml" "selene.toml" ".git")) (command . "lua-language-server") (args) (config . "{\"Lua\": {\"hint\": {\"arrayIndex\": \"Enable\", \"await\": true, \"enable\": true, \"paramName\": \"All\", \"paramType\": true, \"setType\": true}}}"))
 ("luau" (languages ("luau" "aftman.toml" "default.project.json" "wally.toml" "rokit.toml" "selene.toml" ".darklua.json" "foreman.toml" ".luaurc")) (command . "luau-lsp") (args "lsp") (config))
 ("markdoc-ls" (languages ("markdoc")) (command . "markdoc-ls") (args "--stdio") (config))
 ("marksman" (languages ("markdown" ".marksman.toml")) (command . "marksman") (args "server") (config))
 ("mesonlsp" (languages ("meson")) (command . "mesonlsp") (args "--lsp") (config))
 ("metals" (languages ("scala" "build.sbt" "build.sc" "build.gradle" "build.gradle.kts" "pom.xml" ".scala-build")) (command . "metals") (args) (config . "{\"isHttpEnabled\": true, \"metals\": {\"inlayHints\": {\"hintsInPatternMatch\": {\"enable\": true}, \"typeParameters\": {\"enable\": true}}}}"))
 ("millet" (languages ("sml" "millet.toml")) (command . "millet-ls") (args) (config))
 ("mint" (languages ("mint")) (command . "mint") (args "tool" "ls") (config))
 ("mm-lsp-server" (languages ("metamath" "set.mm")) (command . "mm-lsp-server") (args) (config))
 ("mojo-lsp-server" (languages ("mojo" "pixi.toml" "pixi.lock")) (command . "pixi") (args "run" "mojo-lsp-server") (config))
 ("moonbit-lsp" (languages ("moonbit" "moon.mod.json")) (command . "moonbit-lsp") (args) (config))
 ("neocmakelsp" (languages ("cmake")) (command . "neocmakelsp") (args "stdio") (config))
 ("nginx-language-server" (languages ("nginx" "nginx.conf")) (command . "nginx-language-server") (args) (config))
 ("nil" (languages ("nix")) (command . "nil") (args) (config))
 ("nimlangserver" (languages ("nim")) (command . "nimlangserver") (args) (config))
 ("nls" (languages ("nickel")) (command . "nls") (args) (config))
 ("nu-lsp" (languages ("nu")) (command . "nu") (args "--lsp") (config))
 ("ocamllsp" (languages ("ocaml") ("ocaml-interface")) (command . "ocamllsp") (args) (config))
 ("ols" (languages ("odin" "ols.json" "main.odin")) (command . "ols") (args) (config))
 ("openscad-lsp" (languages ("openscad")) (command . "openscad-lsp") (args "--stdio") (config))
 ("pasls" (languages ("pascal")) (command . "pasls") (args) (config))
 ("perlnavigator" (languages ("perl")) (command . "perlnavigator") (args "--stdio") (config))
 ("pest-language-server" (languages ("pest")) (command . "pest-language-server") (args) (config))
 ("pkl-lsp" (languages ("pkl")) (command . "pkl-lsp") (args) (config))
 ("pony-lsp" (languages ("ponylang" "corral.json" "lock.json")) (command . "pony-lsp") (args "--stdio") (config . "{\"pony-lsp\": {\"defines\": [], \"ponypath\": []}}"))
 ("prisma-language-server" (languages ("prisma" "package.json")) (command . "prisma-language-server") (args "--stdio") (config . "{\"prisma\": {\"enableDiagnostics\": true}}"))
 ("puppet-languageserver" (languages ("puppet")) (command . "puppet-languageserver") (args "--stdio") (config))
 ("purescript-language-server" (languages ("purescript" "spago.yaml" "spago.dhall" "bower.json")) (command . "purescript-language-server") (args "--stdio") (config))
 ("pylsp" (languages ("snakemake" "Snakefile" "config.yaml" "environment.yaml" "workflow/")) (command . "pylsp") (args) (config))
 ("qmlls" (languages ("qml")) (command . "qmlls") (args) (config))
 ("quint-language-server" (languages ("quint")) (command . "quint-language-server") (args "--stdio") (config))
 ("r" (languages ("r") ("rmarkdown")) (command . "R") (args "--vanilla" "--no-echo" "-e" "languageserver::run()") (config))
 ("racket" (languages ("racket")) (command . "racket") (args "-l" "racket-langserver") (config))
 ("regols" (languages ("rego")) (command . "regols") (args) (config))
 ("rescript-language-server" (languages ("rescript" "bsconfig.json")) (command . "rescript-language-server") (args "--stdio") (config))
 ("ripple-lsp" (languages ("ripple" "package.json")) (command . "ripple-language-server") (args "--stdio") (config))
 ("robotcode" (languages ("robot")) (command . "robotcode") (args "language-server" "--stdio") (config))
 ("ron-lsp" (languages ("ron" "Cargo.toml")) (command . "ron-lsp") (args) (config))
 ("roslyn-language-server" (languages ("c-sharp" "*.slnx" "*.sln" "*.csproj")) (command . "roslyn-language-server") (args "--stdio" "--autoLoadProjects") (config))
 ("rshtml-analyzer" (languages ("rshtml" "Cargo.lock" "Cargo.toml")) (command . "rshtml-analyzer") (args "--stdio") (config))
 ("ruby-lsp" (languages ("ruby")) (command . "ruby-lsp") (args) (config))
 ("rust-analyzer" (languages ("rust" "Cargo.toml" "Cargo.lock")) (command . "rust-analyzer") (args) (config . "{\"files\": {\"watcher\": \"server\"}, \"inlayHints\": {\"bindingModeHints\": {\"enable\": false}, \"closingBraceHints\": {\"minLines\": 10}, \"closureReturnTypeHints\": {\"enable\": \"with_block\"}, \"discriminantHints\": {\"enable\": \"fieldless\"}, \"lifetimeElisionHints\": {\"enable\": \"skip_trivial\"}, \"typeHints\": {\"hideClosureInitialization\": false}}}"))
 ("serve-d" (languages ("d")) (command . "serve-d") (args) (config))
 ("slangd" (languages ("slang")) (command . "slangd") (args) (config))
 ("slint-lsp" (languages ("slint")) (command . "slint-lsp") (args) (config))
 ("smalisp" (languages ("smali")) (command . "smalisp") (args) (config))
 ("solc" (languages ("solidity")) (command . "solc") (args "--lsp") (config))
 ("sourcekit-lsp" (languages ("swift" "Package.swift")) (command . "sourcekit-lsp") (args) (config))
 ("sourcepawn-studio" (languages ("sourcepawn")) (command . "sourcepawn-studio") (args) (config))
 ("spade-language-server" (languages ("spade" "swim.toml")) (command . "swim") (args "lsp") (config))
 ("starpls" (languages ("starlark")) (command . "starpls") (args) (config))
 ("styx" (languages ("styx")) (command . "styx") (args "lsp") (config))
 ("svelteserver" (languages ("svelte")) (command . "svelteserver") (args "--stdio") (config . "{\"configuration\": {\"javascript\": {\"inlayHints\": {\"enumMemberValues\": {\"enabled\": true}, \"functionLikeReturnTypes\": {\"enabled\": true}, \"parameterNames\": {\"enabled\": \"all\"}, \"parameterTypes\": {\"enabled\": true}, \"propertyDeclarationTypes\": {\"enabled\": true}, \"variableTypes\": {\"enabled\": true}}}, \"typescript\": {\"inlayHints\": {\"enumMemberValues\": {\"enabled\": true}, \"functionLikeReturnTypes\": {\"enabled\": true}, \"parameterNames\": {\"enabled\": \"all\"}, \"parameterTypes\": {\"enabled\": true}, \"propertyDeclarationTypes\": {\"enabled\": true}, \"variableTypes\": {\"enabled\": true}}}}}"))
 ("svlangserver" (languages ("systemverilog")) (command . "svlangserver") (args) (config . "{\"systemverilog\": {\"includeIndexing\": [\"*.{v,vh,sv,svh}\", \"**/*.{v,vh,sv,svh}\"]}}"))
 ("swipl" (languages ("prolog")) (command . "swipl") (args "-g" "use_module(library(lsp_server))" "-g" "lsp_server:main" "-t" "halt" "--" "stdio") (config))
 ("systemd-lsp" (languages ("systemd")) (command . "systemd-lsp") (args) (config))
 ("taplo" (languages ("toml") ("jjconfig") ("miseconfig") ("cross-config") ("git-cliff-config")) (command . "taplo") (args "lsp" "stdio") (config))
 ("teal-language-server" (languages ("teal" "tlconfig.lua")) (command . "teal-language-server") (args) (config))
 ("templ" (languages ("templ" "go.work" "go.mod")) (command . "templ") (args "lsp") (config))
 ("termux-language-server" (languages ("pkgbuild")) (command . "termux-language-server") (args) (config))
 ("terraform-ls" (languages ("hcl") ("tfvars")) (command . "terraform-ls") (args "serve") (config))
 ("texlab" (languages ("latex") ("bibtex")) (command . "texlab") (args) (config))
 ("tilt" (languages ("tilt")) (command . "tilt") (args "lsp" "start") (config))
 ("tinymist" (languages ("typst")) (command . "tinymist") (args) (config))
 ("ts_query_ls" (languages ("tsq")) (command . "ts_query_ls") (args) (config))
 ("ty" (languages ("python" "pyproject.toml" "setup.py" "poetry.lock" "pyrightconfig.json")) (command . "ty") (args "server") (config))
 ("typescript-language-server" (languages ("javascript" "package.json" "jsconfig.json") ("jsx" "package.json" "jsconfig.json") ("typescript" "package.json" "tsconfig.json") ("tsx" "package.json" "tsconfig.json") ("gjs" "package.json" "ember-cli-build.js") ("gts" "package.json" "ember-cli-build.js")) (command . "typescript-language-server") (args "--stdio") (config . "{\"hostInfo\": \"hume\", \"javascript\": {\"inlayHints\": {\"includeInlayEnumMemberValueHints\": true, \"includeInlayFunctionLikeReturnTypeHints\": true, \"includeInlayFunctionParameterTypeHints\": true, \"includeInlayParameterNameHints\": \"all\", \"includeInlayParameterNameHintsWhenArgumentMatchesName\": true, \"includeInlayPropertyDeclarationTypeHints\": true, \"includeInlayVariableTypeHints\": true}}, \"typescript\": {\"inlayHints\": {\"includeInlayEnumMemberValueHints\": true, \"includeInlayFunctionLikeReturnTypeHints\": true, \"includeInlayFunctionParameterTypeHints\": true, \"includeInlayParameterNameHints\": \"all\", \"includeInlayParameterNameHintsWhenArgumentMatchesName\": true, \"includeInlayPropertyDeclarationTypeHints\": true, \"includeInlayVariableTypeHints\": true}}}"))
 ("typespec" (languages ("typespec" "tspconfig.yaml")) (command . "tsp-server") (args "--stdio") (config))
 ("vala-language-server" (languages ("vala")) (command . "vala-language-server") (args) (config))
 ("varlink-language-server" (languages ("varlink")) (command . "varlink-language-server") (args) (config))
 ("verible-verilog-ls" (languages ("verilog")) (command . "verible-verilog-ls") (args) (config))
 ("vhdl_ls" (languages ("vhdl")) (command . "vhdl_ls") (args) (config))
 ("vlang-language-server" (languages ("v" "v.mod")) (command . "v-analyzer") (args) (config))
 ("vscode-css-language-server" (languages ("css") ("scss") ("less")) (command . "vscode-css-language-server") (args "--stdio") (config . "{\"css\": {\"validate\": {\"enable\": true}}, \"provideFormatter\": true}"))
 ("vscode-html-language-server" (languages ("html")) (command . "vscode-html-language-server") (args "--stdio") (config . "{\"provideFormatter\": true}"))
 ("vscode-json-language-server" (languages ("json") ("jsonc") ("json-ld")) (command . "vscode-json-language-server") (args "--stdio") (config . "{\"json\": {\"validate\": {\"enable\": true}}, \"provideFormatter\": true}"))
 ("vuels" (languages ("vue" "package.json")) (command . "vue-language-server") (args "--stdio") (config . "{\"typescript\": {\"tsdk\": \"node_modules/typescript/lib/\"}}"))
 ("wasm-language-tools" (languages ("wat")) (command . "wat_server") (args) (config))
 ("wgsl-analyzer" (languages ("wgsl")) (command . "wgsl-analyzer") (args) (config))
 ("wikitext-lsp" (languages ("wikitext")) (command . "wikitext-lsp") (args "--stdio") (config))
 ("yaml-language-server" (languages ("yaml") ("gitlab-ci") ("woodpecker-ci")) (command . "yaml-language-server") (args "--stdio") (config))
 ("yls" (languages ("yara")) (command . "yls") (args "-vv") (config))
 ("zls" (languages ("zig" "build.zig")) (command . "zls") (args) (config))
)
