;;; runtime/scheme/lsp-servers.scm — HUME bundled LSP server registration catalog.
;;;
;;; PURE DATA. One literal sexpr — a list of per-server tagged alists:
;;;
;;;   (name
;;;    (languages (lang-name root-marker…)…)
;;;    (command . cmd)
;;;    (args arg…)
;;;    (settings (key . value)…))
;;;
;;; Absent/empty fields are the empty tail — (args), (settings) — never #f.
;;; All fields are fully canonicalised; no defaults are applied at read time.
;;; Read via the R7RS idiom from any plugin:
;;;
;;;   (define *lsp-servers*
;;;     (call-with-input-file
;;;       (path-join (runtime-dir) "scheme" "lsp-servers.scm")
;;;       read))
;;;
;;; One server per language — Helix's first-listed ("primary") language-server
;;; only; see docs/LSP-INSTALL.md "v1 scope" for the multi-server rationale.
;;; Install sources (download/build info) live in lsp-sources.scm, joined by
;;; server name.
;;;
;;; Source: helix-editor/helix languages.toml @ 8c41b1160792
;;; Full sync: run scripts/sync-grammars.py after updating helix-pin.scm.

(
 ("actions-language-server" (languages ("github-action")) (command . "actions-languageserver") (args "--stdio") (settings (actions-language-server (sessionToken . ""))))
 ("ada-gpr-language-server" (languages ("gpr" "alire.toml")) (command . "ada_language_server") (args "--language-gpr") (settings))
 ("ada-language-server" (languages ("ada" "alire.toml")) (command . "ada_language_server") (args) (settings))
 ("amber-lsp" (languages ("amber")) (command . "amber-lsp") (args) (settings))
 ("asm-lsp" (languages ("nasm") ("gas")) (command . "asm-lsp") (args) (settings))
 ("astro-ls" (languages ("astro")) (command . "astro-ls") (args "--stdio") (settings (typescript (tsdk . "node_modules/typescript/lib"))))
 ("awk-language-server" (languages ("awk")) (command . "awk-language-server") (args) (settings))
 ("bash-language-server" (languages ("bash")) (command . "bash-language-server") (args "start") (settings))
 ("bass" (languages ("bass")) (command . "bass") (args "--lsp") (settings))
 ("beancount-language-server" (languages ("beancount")) (command . "beancount-language-server") (args) (settings))
 ("bicep-langserver" (languages ("bicep")) (command . "bicep-langserver") (args) (settings))
 ("bitbake-language-server" (languages ("bitbake")) (command . "bitbake-language-server") (args) (settings))
 ("blueprint-compiler" (languages ("blueprint")) (command . "blueprint-compiler") (args "lsp") (settings))
 ("buf" (languages ("protobuf")) (command . "buf") (args "lsp" "serve" "--timeout" "0") (settings))
 ("c3-lsp" (languages ("c3" "project.json")) (command . "c3-lsp") (args) (settings))
 ("cairo-language-server" (languages ("cairo")) (command . "cairo-language-server") (args) (settings))
 ("circom-lsp" (languages ("circom" "package.json")) (command . "circom-lsp") (args) (settings))
 ("cl-lsp" (languages ("common-lisp")) (command . "cl-lsp") (args) (settings))
 ("clangd" (languages ("c") ("cpp") ("opencl")) (command . "clangd") (args) (settings))
 ("clarinet" (languages ("clarity" "Clarinet.toml")) (command . "clarinet") (args "lsp") (settings))
 ("clojure-lsp" (languages ("clojure" "project.clj" "build.boot" "deps.edn" "shadow-cljs.edn")) (command . "clojure-lsp") (args) (settings))
 ("codeql" (languages ("codeql")) (command . "codeql") (args "execute" "language-server" "--check-errors=ON_CHANGE") (settings))
 ("commit-lsp" (languages ("git-commit")) (command . "commit-lsp") (args "run") (settings))
 ("crystalline" (languages ("crystal" "shard.yml" "shard.lock")) (command . "crystalline") (args "--stdio") (settings))
 ("cs" (languages ("smithy" "smithy-build.json")) (command . "cs") (args "launch" "--contrib" "smithy-language-server" "--" "0") (settings))
 ("cuelsp" (languages ("cue" "cue.mod")) (command . "cue") (args "lsp" "serve") (settings))
 ("dart" (languages ("dart" "pubspec.yaml")) (command . "dart") (args "language-server" "--client-id=helix") (settings))
 ("dhall-lsp-server" (languages ("dhall")) (command . "dhall-lsp-server") (args) (settings))
 ("djlsp" (languages ("htmldjango" "manage.py")) (command . "djlsp") (args) (settings))
 ("docker-compose-langserver" (languages ("docker-compose" "docker-compose.yaml" "docker-compose.yml" "compose.yaml" "compose.yml")) (command . "docker-compose-langserver") (args "--stdio") (settings))
 ("docker-langserver" (languages ("dockerfile" "Dockerfile" "Containerfile")) (command . "docker-langserver") (args "--stdio") (settings))
 ("docker-language-server" (languages ("docker-bake")) (command . "docker-language-server") (args "start" "--stdio") (settings))
 ("dot-language-server" (languages ("dot")) (command . "dot-language-server") (args "--stdio") (settings))
 ("drools-lsp" (languages ("drools" "pom.xml" ".git")) (command . "drools-lsp") (args) (settings))
 ("dts-lsp" (languages ("devicetree")) (command . "dts-lsp") (args) (settings))
 ("earthlyls" (languages ("earthfile" "Earthfile")) (command . "earthlyls") (args) (settings))
 ("ebnfer" (languages ("ebnf")) (command . "ebnfer") (args) (settings))
 ("eiffel-language-server" (languages ("eiffel")) (command . "eiffel-language-server") (args) (settings))
 ("elixir-ls" (languages ("elixir" "mix.exs" "mix.lock") ("heex" "mix.exs" "mix.lock")) (command . "elixir-ls") (args) (settings (elixirLS (dialyzerEnabled . #f))))
 ("elm-language-server" (languages ("elm" "elm.json")) (command . "elm-language-server") (args) (settings))
 ("elvish" (languages ("elvish")) (command . "elvish") (args "-lsp") (settings))
 ("ember-language-server" (languages ("glimmer" "package.json" "ember-cli-build.js")) (command . "ember-language-server") (args "--stdio") (settings))
 ("erlang-ls" (languages ("erlang" "rebar.config")) (command . "erlang_ls") (args) (settings))
 ("fennel-ls" (languages ("fennel")) (command . "fennel-ls") (args) (settings))
 ("fish-lsp" (languages ("fish")) (command . "fish-lsp") (args "start") (settings))
 ("forc" (languages ("sway" "Forc.toml" "Forc.lock")) (command . "forc") (args "lsp") (settings))
 ("forth-lsp" (languages ("forth")) (command . "forth-lsp") (args) (settings))
 ("fortls" (languages ("fortran" "fpm.toml")) (command . "fortls") (args "--lowercase_intrinsics") (settings))
 ("fsharp-ls" (languages ("fsharp" "*.slnx" "*.sln" "*.fsproj")) (command . "fsautocomplete") (args) (settings (AutomaticWorkspaceInit . #t)))
 ("gleam" (languages ("gleam" "gleam.toml")) (command . "gleam") (args "lsp") (settings))
 ("glsl_analyzer" (languages ("glsl")) (command . "glsl_analyzer") (args) (settings))
 ("gopls" (languages ("go" "go.work" "go.mod") ("gomod") ("gotmpl") ("gowork")) (command . "gopls") (args) (settings (hints (assignVariableTypes . #t) (compositeLiteralFields . #t) (constantValues . #t) (functionTypeParameters . #t) (parameterNames . #t) (rangeVariableTypes . #t))))
 ("graphql-language-service" (languages ("graphql")) (command . "graphql-lsp") (args "server" "-m" "stream") (settings))
 ("hare-lsp" (languages ("hare")) (command . "hare-lsp") (args "-S") (settings))
 ("haskell-language-server" (languages ("haskell" "Setup.hs" "stack.yaml" "cabal.project" "hie.yaml") ("haskell-literate" "Setup.hs" "stack.yaml" "cabal.project" "hie.yaml") ("cabal" "cabal.project" "Setup.hs")) (command . "haskell-language-server-wrapper") (args "--lsp") (settings))
 ("hdls" (languages ("hdl")) (command . "hdls") (args) (settings))
 ("helm_ls" (languages ("helm" "Chart.yaml")) (command . "helm_ls") (args "serve") (settings))
 ("hyprls" (languages ("hyprlang" "hyprland.conf")) (command . "hyprls") (args) (settings))
 ("hyuga" (languages ("hy" "pyproject.toml")) (command . "hyuga") (args) (settings))
 ("idris2-lsp" (languages ("idris")) (command . "idris2-lsp") (args) (settings))
 ("intelephense" (languages ("php" "composer.json" "index.php")) (command . "intelephense") (args "--stdio") (settings))
 ("jdtls" (languages ("java" "pom.xml" "build.gradle" "build.gradle.kts")) (command . "jdtls") (args) (settings))
 ("jq-lsp" (languages ("jq")) (command . "jq-lsp") (args) (settings))
 ("jsonnet-language-server" (languages ("jsonnet" "jsonnetfile.json")) (command . "jsonnet-language-server") (args "-t" "--lint") (settings))
 ("julia" (languages ("julia" "Manifest.toml" "Project.toml")) (command . "julia") (args "--startup-file=no" "--history-file=no" "--quiet" "-e" "using LanguageServer; runserver()") (settings))
 ("just-lsp" (languages ("just")) (command . "just-lsp") (args) (settings))
 ("kcl-lsp" (languages ("kcl")) (command . "kcl-language-server") (args "server" "--stdio") (settings))
 ("koka" (languages ("koka")) (command . "koka") (args "--language-server" "--lsstdio") (settings))
 ("kotlin-language-server" (languages ("kotlin" "settings.gradle" "settings.gradle.kts")) (command . "kotlin-language-server") (args) (settings))
 ("koto-ls" (languages ("koto")) (command . "koto-ls") (args) (settings))
 ("lean" (languages ("lean" "lakefile.lean" "lakefile.toml")) (command . "lake") (args "serve") (settings))
 ("lua-language-server" (languages ("lua" ".luarc.json" ".luacheckrc" ".stylua.toml" "selene.toml" ".git")) (command . "lua-language-server") (args) (settings (Lua (hint (arrayIndex . "Enable") (await . #t) (enable . #t) (paramName . "All") (paramType . #t) (setType . #t)))))
 ("luau" (languages ("luau" "aftman.toml" "default.project.json" "wally.toml" "rokit.toml" "selene.toml" ".darklua.json" "foreman.toml" ".luaurc")) (command . "luau-lsp") (args "lsp") (settings))
 ("markdoc-ls" (languages ("markdoc")) (command . "markdoc-ls") (args "--stdio") (settings))
 ("marksman" (languages ("markdown" ".marksman.toml")) (command . "marksman") (args "server") (settings))
 ("mesonlsp" (languages ("meson")) (command . "mesonlsp") (args "--lsp") (settings))
 ("metals" (languages ("scala" "build.sbt" "build.sc" "build.gradle" "build.gradle.kts" "pom.xml" ".scala-build")) (command . "metals") (args) (settings (isHttpEnabled . #t) (metals (inlayHints (hintsInPatternMatch (enable . #t)) (typeParameters (enable . #t))))))
 ("mint" (languages ("mint")) (command . "mint") (args "tool" "ls") (settings))
 ("mojo-lsp-server" (languages ("mojo" "pixi.toml" "pixi.lock")) (command . "pixi") (args "run" "mojo-lsp-server") (settings))
 ("neocmakelsp" (languages ("cmake")) (command . "neocmakelsp") (args "stdio") (settings))
 ("nil" (languages ("nix")) (command . "nil") (args) (settings))
 ("nimlangserver" (languages ("nim")) (command . "nimlangserver") (args) (settings))
 ("nls" (languages ("nickel")) (command . "nls") (args) (settings))
 ("nu-lsp" (languages ("nu")) (command . "nu") (args "--lsp") (settings))
 ("ocamllsp" (languages ("ocaml") ("ocaml-interface")) (command . "ocamllsp") (args) (settings))
 ("ols" (languages ("odin" "ols.json" "main.odin")) (command . "ols") (args) (settings))
 ("openscad-lsp" (languages ("openscad")) (command . "openscad-lsp") (args "--stdio") (settings))
 ("pasls" (languages ("pascal")) (command . "pasls") (args) (settings))
 ("perlnavigator" (languages ("perl")) (command . "perlnavigator") (args "--stdio") (settings))
 ("pest-language-server" (languages ("pest")) (command . "pest-language-server") (args) (settings))
 ("pkl-lsp" (languages ("pkl")) (command . "pkl-lsp") (args) (settings))
 ("pony-lsp" (languages ("ponylang" "corral.json" "lock.json")) (command . "pony-lsp") (args "--stdio") (settings (defines ) (ponypath )))
 ("prisma-language-server" (languages ("prisma" "package.json")) (command . "prisma-language-server") (args "--stdio") (settings (prisma (enableDiagnostics . #t))))
 ("purescript-language-server" (languages ("purescript" "spago.yaml" "spago.dhall" "bower.json")) (command . "purescript-language-server") (args "--stdio") (settings))
 ("pylsp" (languages ("snakemake" "Snakefile" "config.yaml" "environment.yaml" "workflow/")) (command . "pylsp") (args) (settings))
 ("qmlls" (languages ("qml")) (command . "qmlls") (args) (settings))
 ("quint-language-server" (languages ("quint")) (command . "quint-language-server") (args "--stdio") (settings))
 ("r" (languages ("r") ("rmarkdown")) (command . "R") (args "--no-echo" "-e" "languageserver::run()") (settings))
 ("racket" (languages ("racket")) (command . "racket") (args "-l" "racket-langserver") (settings))
 ("regols" (languages ("rego")) (command . "regols") (args) (settings))
 ("rescript-language-server" (languages ("rescript" "bsconfig.json")) (command . "rescript-language-server") (args "--stdio") (settings))
 ("ripple-lsp" (languages ("ripple" "package.json")) (command . "ripple-language-server") (args "--stdio") (settings))
 ("robotcode" (languages ("robot")) (command . "robotcode") (args "language-server" "--stdio") (settings))
 ("ron-lsp" (languages ("ron" "Cargo.toml")) (command . "ron-lsp") (args) (settings))
 ("roslyn-language-server" (languages ("c-sharp" "*.slnx" "*.sln" "*.csproj")) (command . "roslyn-language-server") (args "--stdio" "--autoLoadProjects") (settings))
 ("rshtml-analyzer" (languages ("rshtml" "Cargo.lock" "Cargo.toml")) (command . "rshtml-analyzer") (args "--stdio") (settings))
 ("ruby-lsp" (languages ("ruby")) (command . "ruby-lsp") (args) (settings))
 ("rust-analyzer" (languages ("rust" "Cargo.toml" "Cargo.lock")) (command . "rust-analyzer") (args) (settings (files (watcher . "server")) (inlayHints (bindingModeHints (enable . #f)) (closingBraceHints (minLines . 10)) (closureReturnTypeHints (enable . "with_block")) (discriminantHints (enable . "fieldless")) (lifetimeElisionHints (enable . "skip_trivial")) (typeHints (hideClosureInitialization . #f)))))
 ("serve-d" (languages ("d")) (command . "serve-d") (args) (settings))
 ("slangd" (languages ("slang")) (command . "slangd") (args) (settings))
 ("slint-lsp" (languages ("slint")) (command . "slint-lsp") (args) (settings))
 ("smalisp" (languages ("smali")) (command . "smalisp") (args) (settings))
 ("solc" (languages ("solidity")) (command . "solc") (args "--lsp") (settings))
 ("sourcekit-lsp" (languages ("swift" "Package.swift")) (command . "sourcekit-lsp") (args) (settings))
 ("sourcepawn-studio" (languages ("sourcepawn")) (command . "sourcepawn-studio") (args) (settings))
 ("spade-language-server" (languages ("spade" "swim.toml")) (command . "spade-language-server") (args) (settings))
 ("starpls" (languages ("starlark")) (command . "starpls") (args) (settings))
 ("styx" (languages ("styx")) (command . "styx") (args "lsp") (settings))
 ("svelteserver" (languages ("svelte")) (command . "svelteserver") (args "--stdio") (settings (configuration (javascript (inlayHints (enumMemberValues (enabled . #t)) (functionLikeReturnTypes (enabled . #t)) (parameterNames (enabled . "all")) (parameterTypes (enabled . #t)) (propertyDeclarationTypes (enabled . #t)) (variableTypes (enabled . #t)))) (typescript (inlayHints (enumMemberValues (enabled . #t)) (functionLikeReturnTypes (enabled . #t)) (parameterNames (enabled . "all")) (parameterTypes (enabled . #t)) (propertyDeclarationTypes (enabled . #t)) (variableTypes (enabled . #t)))))))
 ("svlangserver" (languages ("systemverilog")) (command . "svlangserver") (args) (settings (systemverilog (includeIndexing "*.{v,vh,sv,svh}" "**/*.{v,vh,sv,svh}"))))
 ("swipl" (languages ("prolog")) (command . "swipl") (args "-g" "use_module(library(lsp_server))" "-g" "lsp_server:main" "-t" "halt" "--" "stdio") (settings))
 ("systemd-lsp" (languages ("systemd")) (command . "systemd-lsp") (args) (settings))
 ("taplo" (languages ("toml") ("jjconfig") ("miseconfig") ("cross-config") ("git-cliff-config")) (command . "taplo") (args "lsp" "stdio") (settings))
 ("teal-language-server" (languages ("teal" "tlconfig.lua")) (command . "teal-language-server") (args) (settings))
 ("templ" (languages ("templ" "go.work" "go.mod")) (command . "templ") (args "lsp") (settings))
 ("termux-language-server" (languages ("pkgbuild")) (command . "termux-language-server") (args) (settings))
 ("terraform-ls" (languages ("hcl") ("tfvars")) (command . "terraform-ls") (args "serve") (settings))
 ("texlab" (languages ("latex") ("bibtex")) (command . "texlab") (args) (settings))
 ("tilt" (languages ("tilt")) (command . "tilt") (args "lsp" "start") (settings))
 ("tinymist" (languages ("typst")) (command . "tinymist") (args) (settings))
 ("ts_query_ls" (languages ("tsq")) (command . "ts_query_ls") (args) (settings))
 ("ty" (languages ("python" "pyproject.toml" "setup.py" "poetry.lock" "pyrightconfig.json")) (command . "ty") (args "server") (settings))
 ("typescript-language-server" (languages ("javascript" "package.json" "jsconfig.json") ("jsx" "package.json" "jsconfig.json") ("typescript" "package.json" "tsconfig.json") ("tsx" "package.json" "tsconfig.json") ("gjs" "package.json" "ember-cli-build.js") ("gts" "package.json" "ember-cli-build.js")) (command . "typescript-language-server") (args "--stdio") (settings (hostInfo . "hume") (javascript (inlayHints (includeInlayEnumMemberValueHints . #t) (includeInlayFunctionLikeReturnTypeHints . #t) (includeInlayFunctionParameterTypeHints . #t) (includeInlayParameterNameHints . "all") (includeInlayParameterNameHintsWhenArgumentMatchesName . #t) (includeInlayPropertyDeclarationTypeHints . #t) (includeInlayVariableTypeHints . #t))) (typescript (inlayHints (includeInlayEnumMemberValueHints . #t) (includeInlayFunctionLikeReturnTypeHints . #t) (includeInlayFunctionParameterTypeHints . #t) (includeInlayParameterNameHints . "all") (includeInlayParameterNameHintsWhenArgumentMatchesName . #t) (includeInlayPropertyDeclarationTypeHints . #t) (includeInlayVariableTypeHints . #t)))))
 ("typespec" (languages ("typespec" "tspconfig.yaml")) (command . "tsp-server") (args "--stdio") (settings))
 ("vala-language-server" (languages ("vala")) (command . "vala-language-server") (args) (settings))
 ("verible-verilog-ls" (languages ("verilog")) (command . "verible-verilog-ls") (args) (settings))
 ("vhdl_ls" (languages ("vhdl")) (command . "vhdl_ls") (args) (settings))
 ("vlang-language-server" (languages ("v" "v.mod")) (command . "v-analyzer") (args) (settings))
 ("vscode-css-language-server" (languages ("css") ("scss") ("less")) (command . "vscode-css-language-server") (args "--stdio") (settings (css (validate (enable . #t))) (provideFormatter . #t)))
 ("vscode-html-language-server" (languages ("html")) (command . "vscode-html-language-server") (args "--stdio") (settings (provideFormatter . #t)))
 ("vscode-json-language-server" (languages ("json") ("jsonc") ("json-ld")) (command . "vscode-json-language-server") (args "--stdio") (settings (json (validate (enable . #t))) (provideFormatter . #t)))
 ("vuels" (languages ("vue" "package.json")) (command . "vue-language-server") (args "--stdio") (settings (typescript (tsdk . "node_modules/typescript/lib/"))))
 ("wasm-language-tools" (languages ("wat")) (command . "wat_server") (args) (settings))
 ("wgsl-analyzer" (languages ("wgsl")) (command . "wgsl-analyzer") (args) (settings))
 ("wikitext-lsp" (languages ("wikitext")) (command . "wikitext-lsp") (args "--stdio") (settings))
 ("yaml-language-server" (languages ("yaml") ("gitlab-ci") ("woodpecker-ci")) (command . "yaml-language-server") (args "--stdio") (settings))
 ("yls" (languages ("yara")) (command . "yls") (args "-vv") (settings))
 ("zls" (languages ("zig" "build.zig")) (command . "zls") (args) (settings))
)
