[package]
name = "hume"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { path = "../engine" }
platform = { path = "../platform" }
scripting = { path = "../scripting" }
editing = { path = "../core" }
globset = "0.4"
tree-sitter = "0.26.8"
slotmap = "1"
steel-core = "0.8.2"
ropey.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
ratatui.workspace = true
crossterm = "0.29"
regex-cursor = "0.1.5"
arboard = "3"

[dev-dependencies]
pretty_assertions = "1.4.1"
proptest = "1.11.0"
insta = "1.47"
tempfile = "3"
scripting = { path = "../scripting", features = ["test-util"] }
