(define (displayln . args) (when (%stdout-safe?) (apply %raw-displayln args)))
(define (display . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-display args))
      (when (%stdout-safe?) (%raw-display (car args)))))
(define (print . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-print args))
      (when (%stdout-safe?) (%raw-print (car args)))))
(define (println . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-println args))
      (when (%stdout-safe?) (%raw-println (car args)))))
(define (write . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-write args))
      (when (%stdout-safe?) (%raw-write (car args)))))
(define (write-string . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-write-string args))
      (when (%stdout-safe?) (%raw-write-string (car args) (current-output-port)))))
(define (write-char . args)
  (if (pair? (cdr args))
      (when (%port-safe? (cadr args)) (apply %raw-write-char args))
      (when (%stdout-safe?) (%raw-write-char (car args) (current-output-port)))))
(define (simple-display . args) (when (%stdout-safe?) (apply %raw-simple-display args)))
(define (simple-displayln . args) (when (%stdout-safe?) (apply %raw-simple-displayln args)))
(define (newline . args)
  (if (pair? args)
      (when (%port-safe? (car args)) (apply %raw-newline args))
      (when (%stdout-safe?) (%raw-newline))))
