;;; runtime/plugins/core/lsp-install/language-servers.scm — each language's ordered LSP server list.
;;; Generated — do not hand-edit. Record format: README.md, this directory.
;;; Source: helix-editor/helix languages.toml @ ba40e547426b

(
 ("ada" (servers ("ada-language-server")))
 ("amber" (servers ("amber-lsp")))
 ("astro" (servers ("astro-ls")))
 ("awk" (servers ("awk-language-server")))
 ("bash" (servers ("bash-language-server")))
 ("bass" (servers ("bass")))
 ("beancount" (servers ("beancount-language-server")))
 ("bibtex" (servers ("texlab")))
 ("bicep" (servers ("bicep-langserver")))
 ("bitbake" (servers ("bitbake-language-server")))
 ("blueprint" (servers ("blueprint-compiler")))
 ("c" (servers ("clangd")))
 ("c-sharp" (servers ("roslyn-language-server") ("omnisharp") ("csharp-ls")))
 ("c3" (servers ("c3-lsp")))
 ("cabal" (servers ("haskell-language-server")))
 ("cairo" (servers ("cairo-language-server")))
 ("circom" (servers ("circom-lsp")))
 ("clarity" (servers ("clarinet")))
 ("clojure" (servers ("clojure-lsp")))
 ("cmake" (servers ("neocmakelsp") ("cmake-language-server")))
 ("codeql" (servers ("codeql")))
 ("common-lisp" (servers ("cl-lsp")))
 ("cpp" (servers ("clangd")))
 ("cross-config" (servers ("taplo") ("tombi")))
 ("crystal" (servers ("crystalline") ("ameba-ls")))
 ("css" (servers ("vscode-css-language-server")))
 ("cue" (servers ("cuelsp")))
 ("d" (servers ("serve-d")))
 ("dart" (servers ("dart")))
 ("debian" (servers ("debian-lsp")))
 ("devicetree" (servers ("dts-lsp")))
 ("dhall" (servers ("dhall-lsp-server")))
 ("docker-bake" (servers ("docker-language-server")))
 ("docker-compose" (servers ("docker-compose-langserver") ("yaml-language-server") ("docker-language-server")))
 ("dockerfile" (servers ("docker-langserver") ("docker-language-server")))
 ("dot" (servers ("dot-language-server")))
 ("drools" (servers ("drools-lsp")))
 ("earthfile" (servers ("earthlyls")))
 ("ebnf" (servers ("ebnfer")))
 ("eiffel" (servers ("eiffel-language-server")))
 ("elixir" (servers ("elixir-ls") ("expert")))
 ("elm" (servers ("elm-language-server")))
 ("elvish" (servers ("elvish")))
 ("erlang" (servers ("erlang-ls" (except-features "document-symbols" "workspace-symbols")) ("elp" (except-features "document-symbols" "workspace-symbols"))))
 ("fennel" (servers ("fennel-ls")))
 ("fish" (servers ("fish-lsp")))
 ("forth" (servers ("forth-lsp")))
 ("fortran" (servers ("fortls")))
 ("fsharp" (servers ("fsharp-ls")))
 ("gas" (servers ("asm-lsp")))
 ("gdscript" (servers ("godot")))
 ("ghostty" (servers ("ghostty-ls")))
 ("git-cliff-config" (servers ("taplo") ("tombi")))
 ("git-commit" (servers ("commit-lsp")))
 ("github-action" (servers ("actions-language-server") ("yaml-language-server") ("zizmor")))
 ("gitlab-ci" (servers ("yaml-language-server") ("gitlab-ci-ls")))
 ("gjs" (servers ("typescript-language-server" (except-features "format" "diagnostics")) ("vscode-eslint-language-server") ("ember-language-server")))
 ("gleam" (servers ("gleam")))
 ("glimmer" (servers ("ember-language-server")))
 ("glsl" (servers ("glsl_analyzer") ("glsld")))
 ("go" (servers ("gopls") ("golangci-lint-lsp")))
 ("gomod" (servers ("gopls")))
 ("gotmpl" (servers ("gopls")))
 ("gowork" (servers ("gopls")))
 ("gpr" (servers ("ada-gpr-language-server")))
 ("graphql" (servers ("graphql-language-service")))
 ("gts" (servers ("typescript-language-server" (except-features "format" "diagnostics")) ("vscode-eslint-language-server") ("ember-language-server")))
 ("hare" (servers ("hare-lsp" (except-features "code-action" "completion" "format" "inlay-hints" "rename-symbol" "workspace-symbols"))))
 ("haskell" (servers ("haskell-language-server")))
 ("haskell-literate" (servers ("haskell-language-server")))
 ("hcl" (servers ("terraform-ls")))
 ("hdl" (servers ("hdls")))
 ("heex" (servers ("elixir-ls") ("expert")))
 ("helm" (servers ("helm_ls")))
 ("html" (servers ("vscode-html-language-server") ("superhtml")))
 ("htmldjango" (servers ("djlsp") ("vscode-html-language-server") ("superhtml")))
 ("hy" (servers ("hyuga")))
 ("hyprlang" (servers ("hyprls")))
 ("idris" (servers ("idris2-lsp")))
 ("java" (servers ("jdtls")))
 ("javascript" (servers ("typescript-language-server")))
 ("jjconfig" (servers ("taplo") ("tombi")))
 ("jq" (servers ("jq-lsp")))
 ("json" (servers ("vscode-json-language-server")))
 ("json-ld" (servers ("vscode-json-language-server")))
 ("jsonc" (servers ("vscode-json-language-server")))
 ("jsonnet" (servers ("jsonnet-language-server")))
 ("jsx" (servers ("typescript-language-server")))
 ("julia" (servers ("julia")))
 ("just" (servers ("just-lsp")))
 ("kcl" (servers ("kcl-lsp")))
 ("koka" (servers ("koka")))
 ("kotlin" (servers ("kotlin-language-server")))
 ("koto" (servers ("koto-ls")))
 ("latex" (servers ("texlab")))
 ("lean" (servers ("lean")))
 ("less" (servers ("vscode-css-language-server")))
 ("lua" (servers ("lua-language-server")))
 ("luau" (servers ("luau")))
 ("markdoc" (servers ("markdoc-ls")))
 ("markdown" (servers ("marksman") ("markdown-oxide") ("rumdl")))
 ("meson" (servers ("mesonlsp")))
 ("metamath" (servers ("mm-lsp-server")))
 ("mint" (servers ("mint")))
 ("miseconfig" (servers ("taplo") ("tombi")))
 ("mojo" (servers ("mojo-lsp-server")))
 ("moonbit" (servers ("moonbit-lsp")))
 ("nasm" (servers ("asm-lsp")))
 ("nginx" (servers ("nginx-language-server")))
 ("nickel" (servers ("nls")))
 ("nim" (servers ("nimlangserver")))
 ("nix" (servers ("nil") ("nixd")))
 ("nu" (servers ("nu-lsp") ("nu-lint")))
 ("ocaml" (servers ("ocamllsp")))
 ("ocaml-interface" (servers ("ocamllsp")))
 ("odin" (servers ("ols")))
 ("opencl" (servers ("clangd")))
 ("openscad" (servers ("openscad-lsp")))
 ("pascal" (servers ("pasls")))
 ("perl" (servers ("perlnavigator")))
 ("pest" (servers ("pest-language-server")))
 ("php" (servers ("intelephense")))
 ("pkgbuild" (servers ("termux-language-server") ("bash-language-server" (except-features "diagnostics"))))
 ("pkl" (servers ("pkl-lsp")))
 ("ponylang" (servers ("pony-lsp")))
 ("prisma" (servers ("prisma-language-server")))
 ("prolog" (servers ("swipl")))
 ("protobuf" (servers ("buf") ("pbkit") ("protols")))
 ("puppet" (servers ("puppet-languageserver")))
 ("purescript" (servers ("purescript-language-server")))
 ("python" (servers ("ty") ("ruff") ("jedi") ("pylsp") ("zuban")))
 ("qml" (servers ("qmlls")))
 ("quint" (servers ("quint-language-server")))
 ("r" (servers ("r")))
 ("racket" (servers ("racket")))
 ("rego" (servers ("regols")))
 ("rescript" (servers ("rescript-language-server")))
 ("ripple" (servers ("ripple-lsp")))
 ("rmarkdown" (servers ("r")))
 ("robot" (servers ("robotcode") ("robotframework_ls")))
 ("ron" (servers ("ron-lsp")))
 ("rshtml" (servers ("rshtml-analyzer") ("vscode-html-language-server") ("superhtml")))
 ("ruby" (servers ("ruby-lsp") ("solargraph")))
 ("rust" (servers ("rust-analyzer")))
 ("scala" (servers ("metals")))
 ("scss" (servers ("vscode-css-language-server")))
 ("slang" (servers ("slangd")))
 ("slint" (servers ("slint-lsp")))
 ("smali" (servers ("smalisp")))
 ("smithy" (servers ("cs")))
 ("sml" (servers ("millet")))
 ("snakemake" (servers ("pylsp")))
 ("solidity" (servers ("solc")))
 ("sourcepawn" (servers ("sourcepawn-studio")))
 ("spade" (servers ("spade-language-server")))
 ("starlark" (servers ("starpls") ("buck2")))
 ("styx" (servers ("styx")))
 ("svelte" (servers ("svelteserver")))
 ("sway" (servers ("forc")))
 ("swift" (servers ("sourcekit-lsp")))
 ("systemd" (servers ("systemd-lsp")))
 ("systemverilog" (servers ("svlangserver") ("verible-verilog-ls")))
 ("teal" (servers ("teal-language-server")))
 ("templ" (servers ("templ")))
 ("tfvars" (servers ("terraform-ls")))
 ("tilt" (servers ("tilt")))
 ("toml" (servers ("taplo") ("tombi")))
 ("tsq" (servers ("ts_query_ls")))
 ("tsx" (servers ("typescript-language-server")))
 ("typescript" (servers ("typescript-language-server")))
 ("typespec" (servers ("typespec")))
 ("typst" (servers ("tinymist")))
 ("v" (servers ("vlang-language-server")))
 ("vala" (servers ("vala-language-server")))
 ("varlink" (servers ("varlink-language-server")))
 ("verilog" (servers ("verible-verilog-ls")))
 ("vhdl" (servers ("vhdl_ls")))
 ("vue" (servers ("vuels")))
 ("wat" (servers ("wasm-language-tools")))
 ("wgsl" (servers ("wgsl-analyzer")))
 ("wikitext" (servers ("wikitext-lsp")))
 ("woodpecker-ci" (servers ("yaml-language-server")))
 ("yaml" (servers ("yaml-language-server") ("ansible-language-server")))
 ("yara" (servers ("yls")))
 ("zig" (servers ("zls")))
)
