;;; runtime/plugins/core/lsp-install/servers.scm — HUME bundled LSP server registration catalog.
;;; Generated — do not hand-edit. Record format: README.md, this directory.
;;; Source: helix-editor/helix languages.toml @ ba40e547426b

(
 ("actions-language-server" (args "--stdio") (config . "{\"sessionToken\": \"\"}"))
 ("ada-gpr-language-server" (args "--language-gpr") (config))
 ("ada-language-server" (args) (config))
 ("amber-lsp" (args) (config))
 ("ameba-ls" (args) (config))
 ("ansible-language-server" (args "--stdio") (config))
 ("asm-lsp" (args) (config))
 ("astro-ls" (args "--stdio") (config . "{\"typescript\": {\"tsdk\": \"node_modules/typescript/lib\"}}"))
 ("awk-language-server" (args) (config))
 ("bash-language-server" (args "start") (config))
 ("bass" (args "--lsp") (config))
 ("beancount-language-server" (args) (config))
 ("bicep-langserver" (args) (config))
 ("bitbake-language-server" (args) (config))
 ("blueprint-compiler" (args "lsp") (config))
 ("buck2" (args "lsp") (config))
 ("buf" (args "lsp" "serve" "--timeout" "0") (config))
 ("c3-lsp" (args) (config))
 ("cairo-language-server" (args) (config))
 ("circom-lsp" (args) (config))
 ("cl-lsp" (args) (config))
 ("clangd" (args) (config))
 ("clarinet" (args "lsp") (config))
 ("clojure-lsp" (args) (config))
 ("cmake-language-server" (args) (config))
 ("codeql" (args "execute" "language-server" "--check-errors=ON_CHANGE") (config))
 ("commit-lsp" (args "run") (config))
 ("crystalline" (args "--stdio") (config))
 ("cs" (args "launch" "--contrib" "smithy-language-server" "--" "0") (config))
 ("csharp-ls" (args) (config))
 ("cuelsp" (args "lsp" "serve") (config))
 ("dart" (args "language-server" "--client-id=helix") (config))
 ("debian-lsp" (args) (config))
 ("dhall-lsp-server" (args) (config))
 ("djlsp" (args) (config))
 ("docker-compose-langserver" (args "--stdio") (config))
 ("docker-langserver" (args "--stdio") (config))
 ("docker-language-server" (args "start" "--stdio") (config))
 ("dot-language-server" (args "--stdio") (config))
 ("drools-lsp" (args) (config))
 ("dts-lsp" (args) (config))
 ("earthlyls" (args) (config))
 ("ebnfer" (args) (config))
 ("eiffel-language-server" (args) (config))
 ("elixir-ls" (args) (config . "{\"elixirLS\": {\"dialyzerEnabled\": false}}"))
 ("elm-language-server" (args) (config))
 ("elp" (args "server") (config))
 ("elvish" (args "-lsp") (config))
 ("ember-language-server" (args "--stdio") (config))
 ("erlang-ls" (args) (config))
 ("expert" (args "--stdio") (config))
 ("fennel-ls" (args) (config))
 ("fish-lsp" (args "start") (config))
 ("forc" (args "lsp") (config))
 ("forth-lsp" (args) (config))
 ("fortls" (args "--lowercase_intrinsics") (config))
 ("fsharp-ls" (args) (config . "{\"AutomaticWorkspaceInit\": true}"))
 ("ghostty-ls" (args) (config))
 ("gitlab-ci-ls" (args) (config))
 ("gleam" (args "lsp") (config))
 ("glsl_analyzer" (args) (config))
 ("glsld" (args "--stdio") (config))
 ("godot" (args "127.0.0.1" "6005") (config))
 ("golangci-lint-lsp" (args) (config . "{\"command\": [\"golangci-lint\", \"run\", \"--output.json.path=stdout\", \"--show-stats=false\", \"--issues-exit-code=1\"]}"))
 ("gopls" (args) (config . "{\"hints\": {\"assignVariableTypes\": true, \"compositeLiteralFields\": true, \"constantValues\": true, \"functionTypeParameters\": true, \"parameterNames\": true, \"rangeVariableTypes\": true}}"))
 ("graphql-language-service" (args "server" "-m" "stream") (config))
 ("hare-lsp" (args "-S") (config))
 ("haskell-language-server" (args "--lsp") (config))
 ("hdls" (args) (config))
 ("helm_ls" (args "serve") (config))
 ("hyprls" (args) (config))
 ("hyuga" (args) (config))
 ("idris2-lsp" (args) (config))
 ("intelephense" (args "--stdio") (config))
 ("jdtls" (args) (config))
 ("jedi" (args) (config))
 ("jq-lsp" (args) (config))
 ("jsonnet-language-server" (args "-t" "--lint") (config))
 ("julia" (args "--startup-file=no" "--history-file=no" "--quiet" "-e" "using LanguageServer; runserver()") (config))
 ("just-lsp" (args) (config))
 ("kcl-lsp" (args "server" "--stdio") (config))
 ("koka" (args "--language-server" "--lsstdio") (config))
 ("kotlin-language-server" (args) (config))
 ("koto-ls" (args) (config))
 ("lean" (args "serve") (config))
 ("lua-language-server" (args) (config . "{\"Lua\": {\"hint\": {\"arrayIndex\": \"Enable\", \"await\": true, \"enable\": true, \"paramName\": \"All\", \"paramType\": true, \"setType\": true}}}"))
 ("luau" (args "lsp") (config))
 ("markdoc-ls" (args "--stdio") (config))
 ("markdown-oxide" (args) (config))
 ("marksman" (args "server") (config))
 ("mesonlsp" (args "--lsp") (config))
 ("metals" (args) (config . "{\"isHttpEnabled\": true, \"metals\": {\"inlayHints\": {\"hintsInPatternMatch\": {\"enable\": true}, \"typeParameters\": {\"enable\": true}}}}"))
 ("millet" (args) (config))
 ("mint" (args "tool" "ls") (config))
 ("mm-lsp-server" (args) (config))
 ("mojo-lsp-server" (args "run" "mojo-lsp-server") (config))
 ("moonbit-lsp" (args) (config))
 ("neocmakelsp" (args "stdio") (config))
 ("nginx-language-server" (args) (config))
 ("nil" (args) (config))
 ("nimlangserver" (args) (config))
 ("nixd" (args) (config))
 ("nls" (args) (config))
 ("nu-lint" (args "--lsp") (config))
 ("nu-lsp" (args "--lsp") (config))
 ("ocamllsp" (args) (config))
 ("ols" (args) (config))
 ("omnisharp" (args "--languageserver") (config))
 ("openscad-lsp" (args "--stdio") (config))
 ("pasls" (args) (config))
 ("pbkit" (args "lsp") (config))
 ("perlnavigator" (args "--stdio") (config))
 ("pest-language-server" (args) (config))
 ("pkl-lsp" (args) (config))
 ("pony-lsp" (args "--stdio") (config . "{\"pony-lsp\": {\"defines\": [], \"ponypath\": []}}"))
 ("prisma-language-server" (args "--stdio") (config . "{\"prisma\": {\"enableDiagnostics\": true}}"))
 ("protols" (args) (config))
 ("puppet-languageserver" (args "--stdio") (config))
 ("purescript-language-server" (args "--stdio") (config))
 ("pylsp" (args) (config))
 ("qmlls" (args) (config))
 ("quint-language-server" (args "--stdio") (config))
 ("r" (args "--vanilla" "--no-echo" "-e" "languageserver::run()") (config))
 ("racket" (args "-l" "racket-langserver") (config))
 ("regols" (args) (config))
 ("rescript-language-server" (args "--stdio") (config))
 ("ripple-lsp" (args "--stdio") (config))
 ("robotcode" (args "language-server" "--stdio") (config))
 ("robotframework_ls" (args) (config))
 ("ron-lsp" (args) (config))
 ("roslyn-language-server" (args "--stdio" "--autoLoadProjects") (config))
 ("rshtml-analyzer" (args "--stdio") (config))
 ("ruby-lsp" (args) (config))
 ("ruff" (args "server") (config))
 ("rumdl" (args "server") (config))
 ("rust-analyzer" (args) (config . "{\"files\": {\"watcher\": \"server\"}, \"inlayHints\": {\"bindingModeHints\": {\"enable\": false}, \"closingBraceHints\": {\"minLines\": 10}, \"closureReturnTypeHints\": {\"enable\": \"with_block\"}, \"discriminantHints\": {\"enable\": \"fieldless\"}, \"lifetimeElisionHints\": {\"enable\": \"skip_trivial\"}, \"typeHints\": {\"hideClosureInitialization\": false}}}"))
 ("serve-d" (args) (config))
 ("slangd" (args) (config))
 ("slint-lsp" (args) (config))
 ("smalisp" (args) (config))
 ("solargraph" (args "stdio") (config))
 ("solc" (args "--lsp") (config))
 ("sourcekit-lsp" (args) (config))
 ("sourcepawn-studio" (args) (config))
 ("spade-language-server" (args "lsp") (config))
 ("starpls" (args) (config))
 ("styx" (args "lsp") (config))
 ("superhtml" (args "lsp") (config))
 ("svelteserver" (args "--stdio") (config . "{\"configuration\": {\"javascript\": {\"inlayHints\": {\"enumMemberValues\": {\"enabled\": true}, \"functionLikeReturnTypes\": {\"enabled\": true}, \"parameterNames\": {\"enabled\": \"all\"}, \"parameterTypes\": {\"enabled\": true}, \"propertyDeclarationTypes\": {\"enabled\": true}, \"variableTypes\": {\"enabled\": true}}}, \"typescript\": {\"inlayHints\": {\"enumMemberValues\": {\"enabled\": true}, \"functionLikeReturnTypes\": {\"enabled\": true}, \"parameterNames\": {\"enabled\": \"all\"}, \"parameterTypes\": {\"enabled\": true}, \"propertyDeclarationTypes\": {\"enabled\": true}, \"variableTypes\": {\"enabled\": true}}}}}"))
 ("svlangserver" (args) (config . "{\"systemverilog\": {\"includeIndexing\": [\"*.{v,vh,sv,svh}\", \"**/*.{v,vh,sv,svh}\"]}}"))
 ("swipl" (args "-g" "use_module(library(lsp_server))" "-g" "lsp_server:main" "-t" "halt" "--" "stdio") (config))
 ("systemd-lsp" (args) (config))
 ("taplo" (args "lsp" "stdio") (config))
 ("teal-language-server" (args) (config))
 ("templ" (args "lsp") (config))
 ("termux-language-server" (args) (config))
 ("terraform-ls" (args "serve") (config))
 ("texlab" (args) (config))
 ("tilt" (args "lsp" "start") (config))
 ("tinymist" (args) (config))
 ("tombi" (args "lsp") (config))
 ("ts_query_ls" (args) (config))
 ("ty" (args "server") (config))
 ("typescript-language-server" (args "--stdio") (config . "{\"hostInfo\": \"hume\", \"javascript\": {\"inlayHints\": {\"includeInlayEnumMemberValueHints\": true, \"includeInlayFunctionLikeReturnTypeHints\": true, \"includeInlayFunctionParameterTypeHints\": true, \"includeInlayParameterNameHints\": \"all\", \"includeInlayParameterNameHintsWhenArgumentMatchesName\": true, \"includeInlayPropertyDeclarationTypeHints\": true, \"includeInlayVariableTypeHints\": true}}, \"typescript\": {\"inlayHints\": {\"includeInlayEnumMemberValueHints\": true, \"includeInlayFunctionLikeReturnTypeHints\": true, \"includeInlayFunctionParameterTypeHints\": true, \"includeInlayParameterNameHints\": \"all\", \"includeInlayParameterNameHintsWhenArgumentMatchesName\": true, \"includeInlayPropertyDeclarationTypeHints\": true, \"includeInlayVariableTypeHints\": true}}}"))
 ("typespec" (args "--stdio") (config))
 ("vala-language-server" (args) (config))
 ("varlink-language-server" (args) (config))
 ("verible-verilog-ls" (args) (config))
 ("vhdl_ls" (args) (config))
 ("vlang-language-server" (args) (config))
 ("vscode-css-language-server" (args "--stdio") (config . "{\"css\": {\"validate\": {\"enable\": true}}, \"provideFormatter\": true}"))
 ("vscode-eslint-language-server" (args "--stdio") (config . "{\"codeAction\": {\"disableRuleComment\": {\"enable\": true, \"location\": \"separateLine\"}, \"showDocumentation\": {\"enable\": true}}, \"experimental\": {\"useFlatConfig\": false}, \"nodePath\": \"\", \"problems\": {\"shortenToSingleLine\": false}, \"rulesCustomizations\": [], \"run\": \"onType\", \"validate\": \"on\", \"workingDirectory\": {\"mode\": \"location\"}}"))
 ("vscode-html-language-server" (args "--stdio") (config . "{\"provideFormatter\": true}"))
 ("vscode-json-language-server" (args "--stdio") (config . "{\"json\": {\"validate\": {\"enable\": true}}, \"provideFormatter\": true}"))
 ("vuels" (args "--stdio") (config . "{\"typescript\": {\"tsdk\": \"node_modules/typescript/lib/\"}}"))
 ("wasm-language-tools" (args) (config))
 ("wgsl-analyzer" (args) (config))
 ("wikitext-lsp" (args "--stdio") (config))
 ("yaml-language-server" (args "--stdio") (config))
 ("yls" (args "-vv") (config))
 ("zizmor" (args "--lsp") (config))
 ("zls" (args) (config))
 ("zuban" (args "server") (config))
)
