#!/usr/bin/env bash
# Fetch and compile tree-sitter grammar fixtures for integration tests.
#
# Grammar revisions and URLs are derived from runtime/scheme/grammar-sources.scm
# (the shipped SSOT, generated by scripts/sync-grammars.py from helix-pin.scm).
# To use a different grammar version, update helix-pin.scm and re-run sync-grammars.py.
#
# Idempotent: skips clone if the dir already exists and is at the correct rev, skips
# compile if the shared library is newer than the grammar source. Run once per
# machine and after any helix-pin bump that changes grammar-sources.scm.
#
# Compiled artifacts go into tests/fixtures/grammars/ (gitignored).
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
FIXTURES="$REPO_ROOT/tests/fixtures/grammars"
GRAMMAR_SOURCES="$REPO_ROOT/runtime/scheme/grammar-sources.scm"
mkdir -p "$FIXTURES"

case "$(uname -s)" in
  Darwin)               EXT="dylib" ;;
  MINGW*|MSYS*|CYGWIN*) EXT="dll"   ;;
  *)                    EXT="so"    ;;
esac

compile_grammar() {
  local name="$1"
  local target="$2"
  local out="$target/parser.$EXT"

  if [[ -f "$out" && "$out" -nt "$target/src/parser.c" ]]; then
    echo "  $name: up to date ($out)"
    return
  fi

  echo "  $name: compiling..."
  tree-sitter build -o "$out" "$target"
  echo "  $name: built $out"
}

fetch_grammar() {
  local name="$1"
  # Derive URL and revision from the shipped grammar catalog.
  local repo rev
  repo=$(awk -F'"' -v n="$name" '$2==n {print $4; exit}' "$GRAMMAR_SOURCES")
  rev=$(awk -F'"' -v n="$name" '$2==n {print $6; exit}' "$GRAMMAR_SOURCES")

  if [[ -z "$repo" || -z "$rev" ]]; then
    echo "error: grammar '$name' not found in $GRAMMAR_SOURCES" >&2
    exit 1
  fi

  local target="$FIXTURES/$name"

  echo "$name (${rev:0:12}):"
  if [[ ! -d "$target" ]]; then
    echo "  cloning..."
    git clone --filter=blob:none --quiet "$repo" "$target"
    git -C "$target" checkout --quiet --force "$rev"
  else
    local current
    current="$(git -C "$target" rev-parse HEAD)"
    if [[ "$current" != "$rev" ]]; then
      git -C "$target" fetch --quiet
      git -C "$target" checkout --quiet --force "$rev"
    fi
  fi
  compile_grammar "$name" "$target"
}

echo "Fetching tree-sitter grammar fixtures..."
fetch_grammar "rust"
fetch_grammar "json"
echo "Done."
