#!/usr/bin/env bash
# Fetch and compile tree-sitter grammar fixtures for integration tests.
#
# Grammar revisions and URLs are derived from runtime/scheme/grammar-sources.scm
# (the shipped SSOT, generated by scripts/sync-grammars.py from helix-pin.scm).
# To use a different grammar version, update helix-pin.scm and re-run sync-grammars.py.
#
# Idempotent: skips clone if the dir already exists and is at the correct rev, skips
# compile if the shared library is newer than the grammar source. Run once per
# machine and after any helix-pin bump that changes grammar-sources.scm.
#
# Compiled artifacts go into tests/fixtures/grammars/ (gitignored). Every
# grammar's queries/ end up at tests/fixtures/grammars/<name>/queries/,
# regardless of whether the grammar lives at the root of its clone or in
# a monorepo subpath — test code can assume a uniform layout and never
# needs to parse grammar-sources.scm for subpaths.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
FIXTURES="$REPO_ROOT/tests/fixtures/grammars"
GRAMMAR_SOURCES="$REPO_ROOT/runtime/scheme/grammar-sources.scm"
mkdir -p "$FIXTURES"

case "$(uname -s)" in
  Darwin)               EXT="dylib" ;;
  MINGW*|MSYS*|CYGWIN*) EXT="dll"   ;;
  *)                    EXT="so"    ;;
esac

compile_grammar() {
  local name="$1"
  local src_dir="$2"
  local out_dir="$3"
  local out="$out_dir/parser.$EXT"

  if [[ -f "$out" && "$out" -nt "$src_dir/src/parser.c" ]]; then
    echo "  $name: up to date ($out)"
    return
  fi

  echo "  $name: compiling..."
  mkdir -p "$out_dir"
  tree-sitter build -o "$out" "$src_dir"
  echo "  $name: built $out"
}

# Grammar-sources.scm entries are 5-tuples: (name url rev symbol subpath).
# `subpath` is the directory within the cloned repo holding the grammar's
# `src/` — most grammars ship at the repo root (subpath == repo basename),
# but monorepos like tree-sitter-markdown hold multiple grammars
# (tree-sitter-markdown, tree-sitter-markdown-inline) as subdirectories of
# one clone.
fetch_grammar() {
  local name="$1"
  local repo rev subpath
  repo=$(awk -F'"' -v n="$name" '$2==n {print $4; exit}' "$GRAMMAR_SOURCES")
  rev=$(awk -F'"' -v n="$name" '$2==n {print $6; exit}' "$GRAMMAR_SOURCES")
  subpath=$(awk -F'"' -v n="$name" '$2==n {print $10; exit}' "$GRAMMAR_SOURCES")

  if [[ -z "$repo" || -z "$rev" ]]; then
    echo "error: grammar '$name' not found in $GRAMMAR_SOURCES" >&2
    exit 1
  fi

  local target="$FIXTURES/$name"

  echo "$name (${rev:0:12}):"
  if [[ ! -d "$target" ]]; then
    echo "  cloning..."
    git clone --filter=blob:none --quiet "$repo" "$target"
    git -C "$target" checkout --quiet --force "$rev"
  else
    local current
    current="$(git -C "$target" rev-parse HEAD)"
    if [[ "$current" != "$rev" ]]; then
      git -C "$target" fetch --quiet
      git -C "$target" checkout --quiet --force "$rev"
    fi
  fi

  local src_dir="$target"
  if [[ -n "$subpath" ]]; then
    src_dir="$target/$subpath"
  fi
  compile_grammar "$name" "$src_dir" "$target"

  # Normalize monorepo grammars (markdown, markdown.inline) so their
  # queries/ live at the fixture root like every other grammar's — copy
  # (not symlink, for Git Bash/Windows) so test code never needs to know
  # about `subpath`; that knowledge stays only in this script.
  if [[ -n "$subpath" && -d "$src_dir/queries" ]]; then
    rm -rf "$target/queries"
    cp -R "$src_dir/queries" "$target/queries"
  fi
}

# Fetch the *Helix-maintained* injections.scm for `name` — distinct from
# (and can differ from!) the grammar's own bundled queries/injections.scm.
# PLUM installs the Helix version, so injection tests need it too — a test
# fixture built from the grammar-bundled file instead would validate a
# query PLUM never actually installs. Best-effort: not every grammar has one.
HELIX_PIN="$(grep -v '^;' "$REPO_ROOT/runtime/scheme/helix-pin.scm" | tr -d '"[:space:]')"
fetch_helix_injections() {
  local name="$1"
  local out="$FIXTURES/$name/helix-injections.scm"
  if [[ -f "$out" ]]; then
    echo "  $name: helix-injections.scm up to date"
    return
  fi
  local url="https://raw.githubusercontent.com/helix-editor/helix/$HELIX_PIN/runtime/queries/$name/injections.scm"
  if curl -fsSL -o "$out" "$url"; then
    echo "  $name: fetched helix-injections.scm"
  else
    rm -f "$out"
    echo "  $name: no injections.scm on Helix (skipped)"
  fi
}

echo "Fetching tree-sitter grammar fixtures..."
fetch_grammar "rust"
fetch_grammar "json"
fetch_grammar "markdown"
fetch_grammar "markdown.inline"
fetch_helix_injections "markdown"
echo "Done."
